public_html/lists/admin/actions/processqueue.php
This pull request changes the way that the new embargo time is calculated when a message is requeued.
It adds a multiple of the requeue interval to the current embargo so that the new value is in the future, i.e. greater than the current time. The benefit of this is that the embargo time is then predictable, e.g. every day at 08:00, instead of drifting forward as it now does.
The sql looks a bit complex but the underlying algorithm is straightforward
* calculate the number of requeue intervals between the current embargo and now - this will usually be between 0 and 1 unless the queue processing has been delayed
* truncate to an integer and add 1
* multiply by the requeue interval
* add to the current embargo
This results in the earliest time in the future that is consistent with the …
=> Mantis 17290 - Predictable embargo time when periodically requeuing a message

public_html/lists/index.php
Adding a regular expression email check on JS before triggering php checks.
=> Added checkEmail JS

public_html/lists/admin/connect.php, public_html/lists/admin/index.php, public_html/lists/admin/netlib.php
Related issues
hard coded image: https://mantis.phplist.org/view.php?id=17741
ip address changed: https://mantis.phplist.org/view.php?id=17742
=> Updated pull request to fix issue with ip address changing for admin when behind a proxy

public_html/lists/admin/defaultplugin.php, public_html/lists/admin/message.php
Added a viewMessage() method to defaultplugin.php
Modified message.php to call each plugin's viewMessage method and include the result in the page. Also, put the sprintf format string into a variable so that it is not repeated.
=> Mantis 0017765: Allow plugins to add to the view message page

public_html/lists/admin/connect.php
Hi there,
I've submitted an enhancement request in mantis https://mantis.phplist.com/view.php?id=17630, it has all the description there. Basically, I modified the phplist slighlty to suit my needs. I thought I might just share what I did and maybe it could help some people. Please let me know what do you think about the patch.
Thank you,
Matheus
=> Tick all the checkboxes under a category when select all lists is ticked

public_html/lists/admin/actions/configure.php, public_html/lists/admin/class.image.inc, public_html/lists/admin/class.phplistmailer.php, public_html/lists/admin/configure.php, public_html/lists/admin/connect.php, public_html/lists/admin/defaultconfig.php, public_html/lists/admin/image.php, public_html/lists/admin/lib.php, public_html/lists/admin/sendemaillib.php
A new settings value: organisation logo
This can hold an image file and be used in templates
[LOGO] - image up to 500
[LOGO:XX] - image up to XX wide or high
requires PHP5.4 or up.
=> feature: [LOGO] placeholder

public_html/lists/admin/sendemaillib.php
Replace admin attribute placeholders when all lists are owned by the same admin.
=> Mantis 16707 - admin attribute placeholders

public_html/lists/admin/about.php, public_html/lists/config/config.php
Thanks to issue report by Nigel Morris-Cotterill, via Anna Morris.
=> Fixed documentation of 'TEST' definition (because true !== 1)

public_html/lists/admin/class.phplistmailer.php
Added two new functions `external_image_exists` & `get_external_image` and moved `EMBEDEXTERNALIMAGES` code from `filesystem_image_exists` & `get_filesystem_image`.
Added defines `EXTERNALIMAGE_MAXAGE`, `EXTERNALIMAGE_TIMEOUT` & `EXTERNALIMAGE_MAXSIZE`.
Added `EMBEDEXTERNALIMAGES` code to `find_html_images` for more specific external image matching allowing for query strings and path info.
=> Rewritten EMBEDEXTERNALIMAGES support

public_html/lists/admin/class.phplistmailer.php
Fix two typos and less strict image matching
=> Fix two typos and less strict image matching

public_html/lists/admin/defaultplugin.php, public_html/lists/admin/index.php
As discuss in previous pull request https://github.com/phpList/phplist3/pull/25, this one is a proposal of implementation of an hook before login page to handle SSO usage (see [#0018027](https://mantis.phplist.org/view.php?id=18027)).
=> Add plugin hook before login page for SSO (#0018027)

public_html/lists/admin/sendemaillib.php
Ensure admin attribute placeholders are always replaced.
=> Mantis 18124 - Admin attribute placeholder not removed

public_html/lists/admin/lib.php
This change corrects the conversion of urls to links.
=> Mantis 18132 - System message urls not converted to links correctly

public_html/lists/admin/subscribelib2.php
=> add * to all types of custom attributes required

public_html/lists/admin/users.php
Added simple number formatting to total subscriber count
=> Added number formatting to total subscriber count

public_html/lists/admin/processbounces.php
Fixes: https://mantis.phplist.org/view.php?id=18253
=> Added missing word fixing apparent typo

public_html/lists/admin/class.phplistmailer.php
This change re-uses the curl handle and sets keep alive headers to improve the sending rate when using amazon ses.
I don't know whether the handle can be re-used indefinitely so the handle is closed if curl_exec() returns an error. A new handle will then be created on the next call.
The change also removes redundant and commented-out code.
=> Mantis 18276 - Improve send rate when using AMAZON SES

public_html/lists/admin/connect.php
This change reorders the processing of copying a message so that only those columns that do not use the default value and are not explicitly set are copied.
So the various count columns, ashtml, astext etc, take their default value of 0, and date fields including "sent", which was the original problem, take their default value of null.
=> Mantis 18198 - copy a message fails when STRICT_TRANS_TABLES is enabled

public_html/lists/admin/uclicks.php, public_html/lists/admin/userclicks.php
Changes to some of the queries in uclicks.php and userclicks.php that use group by.
Corrections to queries in order to work with ONLY_FULL_GROUP_BY
Correct sql so that correct totals are returned
=> Mantis 18341 - MySQL 5.7 changes the default sql mode

public_html/lists/admin/connect.php, public_html/lists/admin/mysqli.inc
Issue explicit http status header for 5xx errors for compatibility with fast-cgi
=> Mantis 18344 - make header() calls compatible with fast cgi

public_html/lists/admin/subscribelib2.php
https://mantis.phplist.org/view.php?id=18348
=> add <label for=""></label> to all form objects.

public_html/lists/admin/statsoverview.php
Simply added a missing column title to label the campaign title in the table. It appears it is not possible to have a different table title to the title of the first column using WebblerListing{}, therefore the table has a new title also, as a side-effect.
=> Added missing column title to table column for campaign title

public_html/lists/admin/list.php
Added link to list title for convenience. Link points to same place, with same link title as the magnifying glass icon on dressprow theme ("view members of this list").
=> Linked list title to 'view list members' page

public_html/lists/admin/bouncemgt.php
I need this change to manage styles on other themes.
Before in dressprow:
After in dressprow:
=> add html list styles to " manage bounces " page

public_html/lists/admin/inc/interfacelib.php, public_html/lists/admin/members.php
- Switched to single row layout for subscribers; 
- Added number formatting to subscriber count; 
- Added column headings to icons; 
- Added hover titles to icons; 
- Changed subscriber email column heading
The new columns' contents are not centered -- tips on how to center them (e.g. via WebblerListing) appreciated
=> Improving members table layout

public_html/lists/admin/statsoverview.php
- Linked campaign subject to view campaign page; 
- Changed table heading;
- Formatted dates; 
- Moved percentage sign
=> Campaign statistics page add link and formatting

public_html/lists/admin/initialise.php
Removed tab character which starts new email notifications
=> Fixed unnecessary tab

public_html/lists/admin/ui/default/footer.inc, public_html/lists/admin/ui/default/footer_minified.inc
Removed themeswitcher from menu (now moved to Settings page)
=> Removed themeswitcher from menu (now moved to Settings page)

public_html/lists/admin/subscribelib2.php
Handle the checkbox for text on the preferences page correctly, in a similar way to the subscribe page.
=> Mantis 18506 - Problem on preferences page with checkbox for text format

public_html/lists/admin/inc/magic_quotes.php
=> [BUGFIX] Always add slashes to the request parameters

public_html/lists/admin/connect.php
Generate a new UUID when repeating a message.
=> Mantis 18516 - A message that is repeated is given the same UUID

public_html/lists/admin/message.php
Removed empty table cell in each table row
=> Added link from list name to view list page

public_html/lists/admin/message.php
- Changed page title to use campaign title (not subject); 
- Added campaign 'subject' to data table; 
- Added date formatting
=> Changed page title to use campaign title (not subject)

public_html/lists/admin/inc/maillib.php
Handle image url starting with // by adding only the scheme.
=> Mantis 18551 Adding absolute resources

public_html/lists/admin/class.phplistmailer.php
Use the config website value instead of $_SERVER['SERVER_NAME'] to identify external images. Those are not guaranteed to be the same but should generally work.
Also simplified creating the list of image extensions used by the regex patterns.
=> Mantis 18553 - external images when run from command line

public_html/lists/admin/sendemaillib.php
=> Constructing url for click tracking, need to escape &

public_html/lists/admin/send_core.php
this is answering a @samtuke request commented here:
https://github.com/phpList/phplist3/pull/158
=> Sendtabs: show always maximun number of tabs as posible

public_html/lists/admin/init.php, public_html/lists/admin/lib.php
This has two commits
- remove obsolete test for using php 5
- quote placeholder name, remove unnecessary strtoupper() calls, allow value of "0"
=> Mantis 18591 - need to quote user attribute name

public_html/lists/admin/connect.php, public_html/lists/admin/spage.php
#0018532: campaign data does not match width of campaigns 'picture frame'
=> fix 2 design issues: #18532 and #0018731

public_html/lists/admin/pluginlib.php
Do not add a new plugin to the array of enabled plugins.
Simplify code by using $pluginInstance instead of $GLOBALS['allplugins'][$className].
=> Mantis 18839 - plugin menu items

public_html/lists/admin/actions/statsoverview.php
Added percentages to views, clicks, and bounces columns;
Moved date into dedicated column
=> Compacted statistics table (removed row)

public_html/lists/admin/sendemaillib.php
Add to email header 
<meta content="width=device-width"/>
To get a better Responsive Design support
=> For better Responsive Design email support

public_html/lists/admin/mviews.php
Switch to newer translation function
=> Replace $GLOBALS['I18N']->get() with s()

public_html/lists/admin/mviews.php
This makes better use of available screen space using both Dressprow and Trevelin themes, also on mobile devices
=> Increased email address crop limit to 35

public_html/lists/admin/init.php, public_html/lists/config/config.php, public_html/lists/config/config_extended.php, public_html/lists/index.php
=> Not send email confirmation

public_html/lists/admin/actions/updatetranslation.php, public_html/lists/admin/updatetranslation.php
Display only installed languages each of which can be updated.
Use a WebblerListing to show the results.
=> Rework of the Update translations page

public_html/lists/admin/class.phplistmailer.php, public_html/lists/admin/init.php, public_html/lists/config/config_extended.php
On server accepting only pop-before-smtp, this patch allowed to mail
=> Add Pop-Before-Smtp Connection

public_html/lists/admin/init.php, public_html/lists/admin/processbounces.php, public_html/lists/config/config_extended.php
I got a problem with a bad rule, deleting bounce, (which i don't),
This help me to find the bad rule.
=> Feature to receive deletebounce for debugging rule

public_html/lists/admin/userhistory.php
https://mantis.phplist.org/view.php?id=18011
=> Replace "Messages" with "Campaigns" in user history table

public_html/lists/admin/import1.php
* Added missing space between words
* Added missing full stop
* Removed duplicate colon
* Moved subheading to directly above corresponding items
* Merged two lines of explanatory text into one
=> Fixed typos and improved subeading formatting

public_html/lists/admin/actions/statsoverview.php
- Replaced $GLOBALS['I18N']->get() with s()
- Added number formatting to stats (cast vars to int and then apply number_format() )
- Changed col heading 'views' to 'unique views'
=> Stats overview formatting

public_html/lists/admin/userhistory.php
* Formatted dates
* Added translation of strings used by 'blacklist info' data names
* Migrated to s() for translation of strings
* Removed leading newline/break from info table row
* Made 1st column labels bold; Removed colons as labels
* Used html special chars decoding to avoid literal printing of special chars in browsers
* Improved formatting/readability of long lines
=> Userhistory tweaks

public_html/lists/admin/attributes.php
- add conceptual help icon for the [predefined defaults](https://mantis.phplist.org/view.php?id=18907)
- Migrated to s() to translate the strings
=> Attributes improvement

public_html/lists/admin/setup.php
https://mantis.phplist.org/view.php?id=19044 & 
https://mantis.phplist.org/view.php?id=18308
=> Replace "Go there" links with linked page titles and add table headings

public_html/lists/admin/messages.php
https://mantis.phplist.org/view.php?id=19046
=> Link campaign statistics from page to more detailed stats

public_html/lists/admin/mviews.php
https://mantis.phplist.org/view.php?id=18627
=> Add button link to campaign statistics page on View Opens page

public_html/lists/admin/list.php
add help button, remove edit and delete buttons.
The help button to work also need this PR to be merged https://github.com/phpList/phplist-lan-help/pull/9
=> #0019064 & #0019062 about "All subscribers" list

public_html/lists/admin/userhistory.php
Mantis: https://mantis.phplist.org/view.php?id=19085
=> 0019085: Replace seconds with formatted date on Subscriber History page

public_html/lists/admin/actions/mclicks.php, public_html/lists/admin/mclicks.php
Mantis issue: https://mantis.phplist.org/view.php?id=18860
=> Change table name on Campaign click statistics page

.travis.yml, composer.json
The failing test: https://travis-ci.org/phpList/phplist3/jobs/353986178
After the fix: https://travis-ci.org/xh3n1/phplist3/builds/354060410
=> Use stable chrome to fix the failing tests

public_html/lists/admin/templates.php
Mantis: https://mantis.phplist.org/view.php?id=19066
-  Add help icon 
-  Use s( ) function for the translation.
=> 0019066: Add contextual help explaining the meaning of "System" templates

public_html/lists/admin/list.php
https://mantis.phplist.org/view.php?id=19065
=> 0019065: Add help option to explain what does it mean to add a list as "public"

public_html/lists/admin/user.php
* Added inline comments
* Deleted erroneous comment
* Improved SQL layout
* Improved deletion notification text
=> Clarify subsriber deletion code

public_html/lists/admin/mviews.php
Display view times as a single field.
=> Mantis 19117 - Layout of the times of views on the Open Statistics page

public_html/lists/admin/attributes.php
Mantis: https://mantis.phplist.org/view.php?id=19144
=>  Add warning to not add attributes containing sensitive subscriber information

public_html/lists/admin/actions/statsoverview.php, public_html/lists/admin/js/phplistapp.js
https://mantis.phplist.org/view.php?id=18725
=>  Add info buttons to headings on stats overview page

public_html/lists/admin/locale/zh_TW/pagetitles.php
Fix 
catlists
import2
import1
and everything after line 56
=> Translation Fix

public_html/lists/admin/locale/zh_TW/language_info, public_html/lists/admin/locale/zh_TW/pagetitles.php, public_html/lists/admin/locale/zh_TW/phplist.po
=> Update from translate.phplist.org

public_html/lists/admin/index.php, public_html/lists/admin/phpListAdminAuthentication.php
https://mantis.phplist.org/view.php?id=19050
=> Set a "Please enter your credentials" message on login page

public_html/lists/admin/community.php
https://mantis.phplist.org/view.php?id=19163
=> Make all links in the community page open in new tab

public_html/lists/admin/list.php
This change remove the total number of list actually beside the button, and move it to the table title. (see attached image)
=> Resolve 0019139: Categorize lists messes up the page buttons.

public_html/lists/admin/lib.php
https://mantis.phplist.org/view.php?id=19131
=> 0019131: resetMessageStatistics() should remove rows from user_message_view

composer.json, public_html/lists/admin/message.php
fix https://mantis.phplist.org/view.php?id=19197
=> Display campaign subject when clicking view campaign and fix the chrome tests failing 

public_html/lists/admin/export.php, public_html/lists/admin/js/phplistapp.js
https://mantis.phplist.org/view.php?id=19188
=> 0019188: Change default option on "export" page to "Any date (Export all subscribers) "

public_html/lists/admin/mviews.php
https://mantis.phplist.org/view.php?id=19210
=> Make dates on 'View opens' page human readable

public_html/lists/admin/attributes.php, public_html/lists/admin/data/termsofservice.txt, public_html/lists/admin/defaults.php
https://mantis.phplist.org/view.php?id=19033
=> 0019033: Provide default attribute for required attribute: consent to terms of service

public_html/lists/admin/user.php
https://mantis.phplist.org/view.php?id=19229
Add a link to the Subscriber Details page to the public personalised preferences page for that subscriber. This makes it easier for administrators to access and provide this link to subscribers should they request it in order to rectify inaccurate records.
=> Add link to subscriber's public preferences page from their subscriber details

public_html/lists/admin/initialise.php, public_html/lists/admin/lib.php, public_html/lists/admin/upgrade.php
https://mantis.phplist.org/view.php?id=19187
=> 0019187: Add draft campaign for use with invite plugin available in new installations

public_html/lists/admin/data/subscriberisanadult.txt, public_html/lists/admin/defaults.php
https://mantis.phplist.org/view.php?id=19226
=> add subscriber is an adult as a default attribute

public_html/lists/index.php
https://mantis.phplist.org/view.php?id=19205
=> add subscription list to 'Subscription already confirmed page'

public_html/lists/admin/actions/statsoverview.php
https://mantis.phplist.org/view.php?id=17824
=> use both subject and meta title on stats overview page if they are different

public_html/lists/admin/data/countries.txt
https://mantis.phplist.org/view.php?id=19239
=>  update the list of the countries

public_html/lists/admin/attributes.php
https://mantis.phplist.org/view.php?id=19144
=>  add the "Read more" link that explains the GDPR compliance 

public_html/lists/index.php
https://mantis.phplist.org/view.php?id=19211
=> support translation for some alert messages

public_html/lists/admin/upgrade.php
https://mantis.phplist.org/view.php?id=19253
=> Fix the error when upgrading from a dev version

public_html/lists/admin/importsimple.php
-Add option to select whether imported subscribers are confirmed or unconfirmed. (the default selected option is confirmed).
-Moved the "import emails" button from top to the bottom.
https://mantis.phplist.org/view.php?id=19231
=> Add option on simple import to select whether imported subscribers are confirmed or unconfirmed 

public_html/lists/admin/actions/export.php, public_html/lists/admin/export.php
https://mantis.phplist.org/view.php?id=19243
=> show busy image when exporting subscribers

public_html/lists/admin/setup.php
https://mantis.phplist.org/view.php?id=19245
=> Remove 'Change admin password' from Checklist page

public_html/lists/admin/inc/userlib.php
https://mantis.phplist.org/view.php?id=19240
=> set blacklisted to 1 in user table if the new subscriber is blacklisted in blacklist table

public_html/lists/admin/user.php
https://mantis.phplist.org/view.php?id=19212
=> Make dates on 'Subscriber details' page human readable

public_html/lists/admin/subscribelib2.php, public_html/lists/admin/user.php
Fix #264 https://mantis.phplist.org/view.php?id=19113
=> fix corrupted attributes using context-aware escaping

.travis.yml, composer.json, public_html/lists/admin/PHPMailer/PHPMailerAutoload.php
Resolved the merge conflicts in #254
=> add compatibility to PHP 7.2 and higher

public_html/lists/admin/actions/mclicks.php
https://mantis.phplist.org/view.php?id=19269
=> fix campaign click statistics export

public_html/lists/admin/spageedit.php
https://mantis.phplist.org/view.php?id=19265
=> select 'Don't offer choice, default to HTML' by default

public_html/lists/admin/configure.php
https://mantis.phplist.org/view.php?id=19242
=> Prevent "Reset to Default" button to change the administrator email.

public_html/lists/admin/defaultFrontendTexts.php, public_html/lists/index.php
https://mantis.phplist.org/view.php?id=19257
=> Make "contact administrator" translatable on subscribe page

public_html/lists/admin/spageedit.php
https://mantis.phplist.org/view.php?id=19266
=>  Improve the order of tabs on 'Add new subscribe page'

public_html/lists/index.php
https://mantis.phplist.org/view.php?id=19254
=> use stripslashes for the intro field 

public_html/lists/admin/defaults.php
It will fix the issue described here: https://mantis.phplist.org/view.php?id=19246
=> use getNewAttributeTablename function to increment the tablename of default attributes

public_html/lists/admin/connect.php, tests/features/getting-started/menu.feature
https://mantis.phplist.org/view.php?id=19219
https://mantis.phplist.org/view.php?id=19171
=> Mantis 19219

public_html/lists/admin/messages.php
https://mantis.phplist.org/view.php?id=19283
=> Show delete button on sent campaigns if it is a test

public_html/lists/admin/js/phplistapp.js, public_html/lists/admin/spage.php
https://mantis.phplist.org/view.php?id=19267
=>  Provide 'Reset template' button for subscribe pages

public_html/lists/admin/messages.php
=> Change copy to draft icon

public_html/lists/admin/spage.php
=> Change the title to reset style to default

public_html/lists/admin/user.php
MANTIS ISSUE LINK: https://mantis.phplist.org/view.php?id=18939
BEFORE:
AFTER:
=> #0018939: Whitespace at the end of Subscriber profile page

public_html/lists/admin/connect.php
Mantis issue: https://mantis.phplist.org/view.php?id=19311
=> Make pages and menulinks empty array

public_html/lists/admin/usercheck.php
-Removed the duplicated emails
-Display key column only if its not null
-Removed the "duplicated" continue button
Before:
After :
=> Improve the appearance of user check page

public_html/lists/admin/listbounces.php
Mantis: https://mantis.phplist.org/view.php?id=18023
=> Added csv extension  for "bounces per list" download file

public_html/lists/admin/user.php
mantis: https://mantis.phplist.org/view.php?id=18943
BEFORE
AFTER
=> #18943: style "remove subscriber"

public_html/lists/admin/plugins.php
mantis link: https://mantis.phplist.org/view.php?id=18944
BEFORE:
AFTER:
No changes in Dressprow.
=> #0018944: Style top buttons in manage plugins page

public_html/lists/admin/listbounces.php
Mantis: https://mantis.phplist.org/view.php?id=19340
=> Change "emails" to "addresses"on listbounces page  

public_html/lists/admin/bounces.php
mantis link: https://mantis.phplist.org/view.php?id=19348
BEFORE:
AFTER:
=> #19348 modify action buttons on header of bounces page

public_html/lists/admin/messages.php
https://mantis.phplist.org/view.php?id=18170
=> Added sendstart time to campaigns page

public_html/lists/admin/locale/hu/phplist.po
=> Fatal error in hu translation

public_html/lists/admin/admin.php, public_html/lists/admin/js/phplistapp.js
https://mantis.phplist.org/view.php?id=19061
=> Option to add password on the interface when you create a new admin

public_html/lists/admin/home.php
Signed-off-by: Ares Dragoi <aresdragoj@gmail.com>
=> redacted the reconcileusers link

public_html/lists/admin/actions/mviews.php
Signed-off-by: Silva Arapi <silva.arapi@gmail.com>
=> Changes views to unique views on mviews page

public_html/lists/admin/subscribelib2.php
My apologies for deleting the original PR and repo.. Anyway once I "reset styling to default" the subscribe page loaded the css and I could get it looking right in trevellin.
=> form element ids added for WCAG compliance

doc/README.bounces
mantis ticket: https://mantis.phplist.org/view.php?id=18837
=> Fix typo on '$bounce_unsubscribe_treshold = 3' and replace 'PHPlist' with 'phpList'

CODE_OF_CONDUCT.md, README.md
https://mantis.phplist.org/view.php?id=19417
=> Add code of conduct 

public_html/lists/admin/defaults.php, public_html/lists/admin/inc/userlib.php
As discussed here https://github.com/phpList/phplist3/pull/301
Also made an improvement regarding getNewAttributeTablename.
=> Check if domain is set for terms of service

public_html/lists/admin/defaultconfig.php
Mantis: https://mantis.phplist.org/view.php?id=19484
=> Add info icon on list organisation settings

tests/features/getting-started/menu.feature
Please see:
https://github.com/phpList/phplist-ui-bootlist/pull/79
The PR on bootlist is required to be merged first.
=> Fix config menu test

public_html/lists/admin/template.php
Mantis: https://mantis.phplist.org/view.php?id=19647
=> Show error message if the template title exists

public_html/lists/admin/connect.php
Mantis: https://mantis.phplist.org/view.php?id=19667
=> Change the number of "recently visited" pages from 6 to 3

public_html/lists/admin/mclicks.php
Fix https://mantis.phplist.org/view.php?id=19701 and https://mantis.phplist.org/view.php?id=19702
=>  Campaign click stats minor fixes

public_html/lists/admin/userclicks.php
Mantis: https://mantis.phplist.org/view.php?id=19705
=>  Use separate table columns for 'Clicks' and 'View Subscriber's clicks button'

public_html/lists/admin/actions/statsoverview.php
I will also add the info text to the help repo.
=> Add total clicks to stats overview

public_html/lists/admin/msgbounces.php
Minor wording improvements for message bounces page
=> Msgbounces text tweaks

public_html/lists/admin/defaultconfig.php, public_html/lists/admin/lib.php, public_html/lists/admin/sendemaillib.php, public_html/lists/admin/vCard.php, public_html/lists/index.php
Mantis: https://mantis.phplist.org/view.php?id=19442
**TO DO:**
=> vCard feature

public_html/lists/admin/index.php
=> Use global plugins and add other missing checks

public_html/lists/admin/defaultFrontendTexts.php, public_html/lists/admin/index.php, public_html/lists/admin/lib.php, public_html/lists/admin/sendemaillib.php
- Added text placeholder
- Use defaultfrontendtexts as default.
- Fixed typo
=> Add Text placeholder for Vcard and language fixes

public_html/lists/admin/bouncerules.php
https://mantis.phplist.org/view.php?id=19734
=> Changed the class of Bounce Rules alert

public_html/lists/admin/defaultconfig.php
=> Fix typo and improved wording in transactional message

public_html/lists/admin/js/phplistapp.js
=> Switch to double quotes in phplistapp.js

public_html/lists/admin/defaultsystemtemplate.php, public_html/lists/admin/templates.php
Users can choose from some available default templates to add by clicking the "Add default template" button.
https://mantis.phplist.org/view.php?id=19790
This is a draft PR (Thanks GitHub for this new feature 😃 ) for @suelaP to test the functionality. 
The current values of templates are just for testing and can be updated later from @BrunildaDosti .
=> Add functionality to load default templates

public_html/lists/admin/baseConfiguration.php, public_html/lists/admin/initialise.php, public_html/lists/admin/upgrade.php
A parameter used by the Symfony framework.
=> Save secret in db for phpList4

public_html/lists/admin/js/phplistapp.js
[Mantis](https://mantis.phplist.org) :
=> Function quotes

public_html/lists/admin/defaultsystemtemplate.php
https://mantis.phplist.org/view.php?id=19814
=> Template changes

public_html/lists/.htaccess
Added app.php entrypoint in FileMatch  lists
=> Added app.php entrypoint in htaccess

public_html/lists/admin/lib.php, public_html/lists/admin/sendemaillib.php
Make the organisation name accessible via [ORGANISATION_NAME] placeholder.
https://mantis.phplist.org/view.php?id=19804
=> Add organisation name placeholder

.travis.yml
https://mantis.phplist.org/view.php?id=19836
=>  Add compatibility check for PHP 7.3 on Travis

public_html/lists/admin/vCard.php, public_html/lists/index.php
https://mantis.phplist.org/view.php?id=19883
=> Add http to vCard url

public_html/lists/admin/subscribelib2.php
When validating a subscription display all errors found instead of just one. This is one of the points raised in this forum post https://discuss.phplist.org/t/email-address-removed-if-captcha-wrong/5243
Now shows all errors. In this case
country not selected
list not selected
captcha not entered (this is validation by a plugin)
a disposable email address has been used (again, validation by a plugin)
=> When validating a subscription display all field errors

public_html/lists/admin/sendemaillib.php
https://mantis.phplist.org/view.php?id=19882
=> Support [CONTACTURL] placeholder

README.md, VERSION
=> Release 3.4.2

public_html/lists/admin/checkprerequisites.php, public_html/lists/admin/index.php
- Moved required extensions in checkprerequisites.php.
- Removed some optional ones such as gd, iconv, mbstring etc
=> Move required extensions in checkprerequisites.php file and removed some optional ones

public_html/lists/.htaccess
=> Fix typo in .htaccess

public_html/lists/admin/init.php
https://mantis.phplist.org/view.php?id=19918
=> Update $GLOBALS['jQuery'] version

public_html/lists/admin/bounce.php
=> Remove var_dump function, probably forgotten

public_html/lists/admin/subscribelib2.php
Based on requests from the related issue
https://github.com/phpList/phplist3/pull/522
=> Added data verification for $_GET['list'] and $_GET['htmlemail']

public_html/lists/admin/actions/domainbounces.php, public_html/lists/admin/actions/domainstats.php, public_html/lists/admin/domainbounces.php
- Top 25 domains with the highest number of bounces
- If you click the domain name, you will more detailed data such as:
sent emails, bounces rate and total views.
https://mantis.phplist.org/view.php?id=18026
=> Domain bounces stats

public_html/lists/admin/actions/domainbounces.php
This adds an info icon on the View Rate column added on this PR https://github.com/phpList/phplist3/pull/548
=> help icon for view rate

public_html/lists/admin/configure.php, public_html/lists/admin/lib.php, public_html/lists/admin/plugins.php
Sanitise the plugin category so that it can be used as an html id attribute value
https://mantis.phplist.org/view.php?id=19974
=> Mantis 19974 - Linking from Manage Plugins page to Settings page

tests/features/getting-started/updateTranslations.feature
Add a check for errors on the update translations page.
=> Add a test to check if there is an error when updating translations

public_html/lists/admin/list.php
Make it possible to search for a list by name
https://mantis.phplist.org/view.php?id=19105
=> Search list by name

public_html/lists/admin/messages.php
Added a user-friendly placeholder 
https://mantis.phplist.org/view.php?id=19685
=> Added a search placeholder in campaigns page

public_html/lists/admin/index.php
reload the page with JS on the referrer check failing
https://mantis.phplist.org/view.php?id=19973
=> reload the page on access denied

.travis.yml, tests/features/bootstrap/FeatureContext.php, tests/features/getting-started/add-plugin.feature
Added test for adding and updating plugin, related to:  https://mantis.phplist.org/view.php?id=20004
=> Plugins test

public_html/lists/admin/mclicks.php, public_html/lists/admin/uclicks.php
Link the two pages together for easier discovery of the additional stats.
=> Link the unique clicks column on the campaign click stats page to list of individual subscribers

README.md
Mantis: https://mantis.phplist.org/view.php?id=19492
New PR avoiding conflicts from @BrunildaDosti's branch / PR https://github.com/phpList/phplist3/pull/532.
This introduces a new README.md design from @BrunildaDosti.
=> Apply new README design from brunildadosti branch

composer.json
Update chromedriver to support the latest version of chrome used
=> edit composer.json to update  chromedriver

public_html/lists/admin/actions/mclicks.php, public_html/lists/admin/actions/statsoverview.php, public_html/lists/admin/inc/interfacelib.php, public_html/lists/admin/mclicks.php, public_html/lists/admin/userclicks.php
Add 'download as CSV' button to mclicks page, and use webblerListing class to change output type to tab delimited.
=> Add csv export to mclicks page

.travis.yml
Travis issue with updating Chrome on Trusty: 
https://github.com/travis-ci/travis-ci/issues/9361
=> Chrome version fix

README.md
=> Update stable version

public_html/lists/admin/configure.php, public_html/lists/admin/send_core.php
There are two small fixes.
- correct some html that is missing "="
- correct the display of a select list configuration item that sometimes displays the option value instead of the option text, such as "phplist-ui-bootlist" instead of "Trevellin" see screenshot.
=> Minor corrections

README.md, VERSION
=> Release 3.4.7

composer.json
Update driver version to support latest stable version of Chrome browser
=> update chromedriver version to support chrome 78

public_html/lists/admin/defaultplugin.php, public_html/lists/lt.php
Allow additional processing of a link click by plugins. For example, to record individual clicks of certain URLs.
=> Allow additional processing of a link click by plugins.

VERSION, public_html/lists/admin/about.php
=> Release 3.4.9

public_html/lists/admin/actions/import1.php, public_html/lists/admin/actions/import2.php, public_html/lists/admin/import2.php
Fix for mantis issue: https://mantis.phplist.org/view.php?id=19915
=> add button styling to 'add more emails' option

public_html/lists/admin/actions/import1.php
https://mantis.phplist.org/view.php?id=20153
=> Mantis 21053 - Spurious changes reported by import1 page

README.md, VERSION
=> Release 3.5.2

INSTALL
=> Fix documentation URL

composer.json
=> update chromedriver to support latest version of chrome

README.md, VERSION
=> Release 3.5.4

public_html/lists/admin/list.php
Fix "Save changes" on the lists page.
=> Fix bug on the lists page

public_html/lists/admin/connect.php, public_html/lists/admin/lib.php
Fix bug when selecting all lists or all public lists on the exclude element in the list selection
https://mantis.phplist.org/view.php?id=20221
=> Mantis20221 fix bug

README.md, VERSION
=> Release 3.5.6

public_html/lists/admin/locale/en/phplist.po, tests/features/getting-started/menu.feature
Revise the navigation label on the side nav that points to database structure upgrade.
phpList#698
=> Revise navigation label (ref phpList#698)

public_html/lists/index.php
Allow ajax request to include the list id as discussed in #701
=> Allow ajax request to include the list id

public_html/lists/admin/accesscheck.php, public_html/lists/admin/actions/export.php, public_html/lists/admin/connect.php, public_html/lists/admin/export.php
Add the option to export subscribers on the commandline. This is useful for very big installations, where the UI version times out.
https://mantis.phplist.org/view.php?id=20277
=> Export on commandline

VERSION
=> Release 3.5.8

VERSION
Release 3.5.9 version of phpList
=> Release 3.5.9

public_html/lists/admin/inc/magic_quotes.php
for security, disallow another JS event in texts
=> disable another JS event

.github/workflows/main.yml, .gitignore, .travis.yml, README.md, TESTING.md, Vagrantfile, composer.json, tests/Makefile, tests/behat.yml, tests/ci/config.php, tests/features/bootstrap/FeatureContext.php, tests/features/getting-started/add-plugin.feature, tests/features/getting-started/setup.feature, tests/features/smtp.feature, tests/travis-ci/behat.yml
Move CI from Travis to Github Actions
=> Migrate to GitHub actions

VERSION
Release version 3.6.1 of phpList
=> Release 3.6.1

public_html/lists/admin/locale/en/phplist.po
Currently translated at 91.1% (1982 of 2174 strings)
Translation: phpList/phpList3
Translate-URL: http://translate.phplist.org/projects/phplist/phplist3/en/
=> Translated using Weblate (English)

VERSION
=> Updated version number

public_html/lists/admin/processbounces.php
In bounce processing when identifying the subscriber use the fallback only when the X-ListMember header is not present.
Currently, if the X-ListMember header is present but with a non-existent subscriber then the fall-back processing takes place and can misleadingly find another email address.
In my case, it found the From header address and associated the bounce with that subscriber. It seems to be better to just treat the bounce as an unidentified subscriber instead.
=> Identifying the subscriber for a bounce

.github/workflows/build-release.yml, .github/workflows/main.yml, .github/workflows/s3upload-test.yml, .gitignore, Dockerfile, composer.json, composer.lock, scripts/install-plugins.sh, scripts/run-tests.sh, tests/Makefile, tests/behat.yml
The github action will fire when a tag is created with vX.Y*
=> Add github action to build the phpList package for release

public_html/lists/admin/lib.php, public_html/lists/admin/message.php
=> avoid stored XSS on the message field

public_html/lists/admin/users.php
(cherry picked from commit 678bd0a8d0c1b4688d027a227535e7af8ccfaed0)
Fix for #769
=> verify the token on a delete call

.github/workflows/main.yml, bin/update-composer.sh, composer.lock, public_html/lists/admin/accesscheck.php, public_html/lists/admin/home.php, tests/behat.yml, tests/default.behat.yml, tests/features/bootstrap/ScreenshotContext.php, tests/features/getting-started/menu.feature
=> consider an installer superuser and handle PHP8 better

.github/workflows/build-release.yml, Dockerfile.release, docker/docker-apache-phplist.conf
=> do not remove composer.json when building

VERSION
=> Updated version

.github/workflows/build-release.yml, .gitignore, public_html/lists/admin/.gitignore, public_html/lists/admin/ui/.gitignore, scripts/install-themes.sh
=> Update release pipeline

VERSION
=> Release 3.6.4

composer.lock
=> Release 3.6.6

.github/workflows/build-release.yml, Dockerfile.release, docker/docker-apache-phplist.conf, docker/docker-entrypoint.sh, docker/docker-phplist-config-dev.php, docker/docker-phplist-config-live.php, docker/phplist-crontab, docker/security.conf, scripts/install-plugins.sh, scripts/install-themes.sh
Build and push the Docker image when a release is tagged.
=> Build docker on release

composer.lock
[Fix for #835](https://github.com/phpList/phplist3/issues/835)
=> update bootlist theme

public_html/lists/admin/messages.php
A problem was reported to me about copying a campaign. The action had resulted in two new campaigns, not one.
It turned out that he had been using the browser back button after copying a campaign, and that was causing the duplicate action to be repeated.
1. On the Sent tab click "copy to draft" button for a campagn
2. On the Draft tab edit the new campaign
3. Then use the browser back button
This causes the GET request of step 1) to be repeated, creating another campaign.
This change is to use the same approach as other campaign actions, such as delete, suspend, which redirect after applying the change by using the `$action_result` variable.
=> Redirect after copying a campaign

public_html/lists/admin/locale/en/phplist.po, public_html/lists/admin/locale/fr/phplist.po, public_html/lists/admin/locale/pl/phplist.po, public_html/lists/admin/locale/pt/phplist.po
=> Translations

public_html/lists/admin/tests/shortenText.php
=> add test for shortenText

composer.lock
Ran `composer update` to update dependencies. This pulls in the latest change to Common Plugin which should fix https://github.com/bramley/phplist-plugin-common/issues/17
=> Composer lock file to pull-in plugins

public_html/lists/admin/js/phplistapp.js, public_html/lists/admin/lib.php, public_html/lists/admin/send_core.php
Fixed #896 
Additionally makes it work behind a proxy.
=> verify redirect behind a proxy

public_html/lists/admin/actions/listmembercount.php, public_html/lists/admin/init.php, public_html/lists/admin/js/phplistapp.js, public_html/lists/admin/list.php
With very large subscriber numbers, the list page is slow to load. Load the subscriber numbers asynchronously.
=> Speed up list page

public_html/lists/admin/init.php
disable the updater by default
#907
=> by default switch the updater off, until it is made more robust

public_html/lists/admin/statsoverview.php
=> avoid division by zero

public_html/lists/admin/init.php
=> load powered image on SSL

docker/docker-phplist-config-dev.php, docker/docker-phplist-config-live.php
Sollves #916 for Docker as well
=> set docker to use the powered images on SSL

public_html/lists/admin/actions/processqueue.php
There are three commits:
- I noticed a couple of places where the parameters to the processQueueOutput() function were incorrect
- Replaced  $GLOBALS['I18N']->get() by s()
- Replaced a few uses of a call to sprintf() wrapping s()
=> Tidy-up output of processqueue

public_html/lists/admin/Updater.php, public_html/lists/admin/index.php, public_html/lists/admin/pluginlib.php
Identify whether a plugin is able to update the phplist code, and link to that plugins's update page when a new release is available
#939
=> Allow a plugin to update phplist

composer.lock
Replaces the previous pull request which had not been rebased on the latest commit in the main branch.
=> Update the Common, CKEditor, and Segment plugins

public_html/lists/admin/admin.php, public_html/lists/admin/admins.php
Log an event when an administrator is deleted so that there is a record of it happening.
=> Log an event when an administrator is deleted

public_html/lists/admin/plugins.php
Allow plugins to be installed from GitLab as well as GitHub.
Tested using the plugin mentioned in #846
https://github.com/phpList/phplist3/issues/846
=> Allow plugins to be installed from GitLab

public_html/lists/admin/locale/en/phplist.po, public_html/lists/admin/locale/fr/phplist.po
=> Translations for 3.6.15 

composer.lock
Update the composer.lock file so that the latest versions of Common plugin and Segment plugin will be included.
=> Update Common plugin and Segment plugin

public_html/lists/admin/locale/templates/phplist.pot
=> Update PO template [Weblate]
