- public_html/lists/admin/commonlib/pages/user.php
Use "dateattribute[x]", where x is the attribute id, instead of the attribute name for the html name attribute. The date fields are then referenced as $_POST['dateattribute'][x]['month'] etc, and the novalue field referenced as $_POST['dateattribute'][x]['novalue'].
Remove hidden field as it does not seem to be needed, and was in an incorrect position in the html.
> Mantis 17624 - Subscriber profile page does not update date attribute

- public_html/lists/admin/connect.php
In a similar way to pull request 1, this pull request changes the way that the new embargo is calculated when a message is repeated.
It adds a multiple of the repeat interval to the current embargo so that the new value is in the future, i.e. greater than the current time. The usual case will be to add the repeat interval once, which is the same as the current processing, but when the queue processing has been delayed then a multiple of the repeat interval will be added.
The "repeat exclusion" processing has been simplified a little and also moved to immediately after calculating the embargo. This avoids creating a new message, which is not fully populated, when more than 15 dates are rejected. That processing had a bug that I think stopped the processing moving beyond two dates. In this …
> Mantis 17620 - Predictable embargo time when repeating a message

- public_html/lists/admin/connect.php
When copying rows from messagedata when repeating a message, avoid the 'id' row.
Not sure whether this is better than explicitly setting the value to the new message id, but solves the original problem.
> Mantis 17615 - Messagedata table has incorrect id field

- public_html/lists/admin/defaultplugin.php
- public_html/lists/admin/pluginlib.php
- public_html/lists/admin/plugins.php
Use a method for dependency check so that conditions are evaluated by calling the method, instead of using eval.
On the plugins page display the (first) reason for dependency check failing
> plugin dependency checking

- public_html/lists/index.php
The validateSubscriptionPage() method of the Captcha plugin was being called when the captcha field had not been displayed, and then tried to access a non-existent variable.
This seems to be caused by using subscribelib2.php on all the variations of the preferences page. This change restricts that to only when the preferences form has been submitted, not when the personal location page has been requested.
Also fixed a few undefined index and variable php notices.
> Mantis 17830 - php undefined index notice in plugin

- public_html/lists/admin/defaultplugin.php
- public_html/lists/admin/sendemaillib.php
I have added a hook to sendemaillib.php to allow plugins to modify the cached message.
The plugins are called after the message template, content and remote urls have been processed, but prior to some placeholder processing. So you might want to review whether that is the best place.
Note that the message is passed by reference, so there is no return value from the plugin.
> Mantis 17847 - Allow plugins to modify the cached message

- public_html/lists/admin/actions/plugins.php
When disabling a plugin also disable other plugins that now fail their enabling test, presumably because they have a dependency on the newly-disabled plugin.
> Mantis 17798 - Plugin remains enabled after dependency is not met

- public_html/lists/admin/init.php
- public_html/lists/admin/sendemaillib.php
- public_html/lists/config/config_extended.php
Enable smtp debug in phpmailer to help in diagnosing connection problems. 
Only for test messages. Format output as html so that it is displayed reasonably.
> Add config entry to enable smtp debug for test messages

- public_html/lists/admin/class.phplistmailer.php
> Add option to embed images from external domains

- public_html/lists/admin/actions/processqueue.php
This PR covers the part of the Mantis issue concerning the batch limit being compared with the number of subscribers processed instead of the number of subscribers who have actually been sent an email. Currently sending to  a subset of subscribers, for example using the Segment plugin, takes the same length of time as sending to the full list, apart from any throttle. A comment regarding the throttle also being applied was wrong.
There are three commits. The first and last consist only of making the indentation consistent, the real changes are in the second commit. The approach is to use the number of emails sent for a message when testing whether the batch limit has been reached. If a subscriber is rejected by a plugin then it does not count towards the batch limit, but does count …
> Mantis 17893 Some issues with filtering subscribers when sending

- public_html/lists/admin/domainstats.php
Added table to domain stats page: Domains with most unconfirmed subscribers (descending order).
Also changed format of columns in other tables to merge the percentage into the preceeding column to save space. Bold formatting added to primary statistic, with percentage in brackets.
Note: This was completed to meet a deadline, please check stats. Performance of this page is overall quite slow and this merge makes it slower still. Recommend rewriting sql queries in future to execute a single sql call at script start and reuse all stats via PHP processing for all html tables (rather than making multiple separate queries).
> Added new table to domain stats page & merged columns

- public_html/lists/.htaccess
- public_html/lists/admin/.htaccess
- public_html/lists/admin/actions/.htaccess
- public_html/lists/admin/inc/.htaccess
- public_html/lists/admin/onyxrss/.htaccess
- public_html/lists/admin/plugins/.htaccess
- public_html/lists/config/.htaccess
mod_access_compat may not be loaded in Apache 2.4, hence
the new access control directives must be used.
> [TASK] Make all .htaccess files Apache 2.4 compatible

- public_html/lists/admin/message.php
When resending campaigns, owner permissions were ignored for 'all' and 'allactive' list settings. The queries were changed to respect the constraints.
> Mantis 18088 - Added permission checks for resending campaigns

- public_html/lists/admin/inc/interfacelib.php
- public_html/lists/admin/userhistory.php
This change adds a field to the WebblerListing class for the heading of the left most column (the element heading). This allows different text to be used for the panel title and the column heading, which currently are the same.
There are also changes to the userhistory page to use the new field.
> Mantis 18011 - Change "Messages" to "Message" in user history table

- public_html/lists/admin/list.php
One effect of the change to keep list membership when unsubscribing is that the "confirmed" counts on the Lists page include those who are also blacklisted. I think it is clearer if the "confirmed" count is the number of people who would be sent a campaign.
This change displays the number blacklisted as a third count for each list, and the confirmed and unconfirmed counts reflect those who are not also blacklisted.
> Mantis 17754 - subscriber list information should be maintained when they unsubscribe

- public_html/lists/admin/admins.php
- public_html/lists/admin/index.php
- public_html/lists/admin/phpListAdminAuthentication.php
- public_html/lists/admin/pluginlib.php
These changes fix the problem of admins being read-only on the admins page, and also (I think) simplifies the selection of the admin authentication class.
admins.php - correct the test of whether authentication is being done externally
phpListAdminAuthentication.php - change to not be a plugin, just a class.
pluginlib.php - sets $authenticationplugin only for a "real" plugin. Remove code that handles phpListAdminAuthentication as a plugin.
index.php - now $authenticationplugin is set if a plugin wants to handle authentication, otherwise fallback to the internal class. Use the already-existing instance of the plugin class instead of creating a new one.
> Mantis 17918 - plugins control authentication

- public_html/lists/admin/list.php
Changed "Subscriber lists" page list member stats formatting from:
List name 1 (2 0)
To:
List name 1 (2, 0)
> Added comma separator between statistics

- public_html/lists/admin/inc/userlib.php
The table name in the `userSelect` function was hardcoded to the `user` table.
This results in a database error when a table prefix is define.
> Respect table prefix to create user selection

- public_html/lists/admin/plugins.php
On the Manage Plugins page provide a link to the plugin's configuration settings, only when a plugin is enabled and has configuration settings.
> Mantis 18200 - Provide link to plugin's settings

- public_html/lists/admin/locale/cs/language_info
- public_html/lists/admin/locale/en/language_info
- public_html/lists/admin/locale/es/language_info
- public_html/lists/admin/locale/it/language_info
- public_html/lists/admin/locale/pl/language_info
- public_html/lists/admin/locale/pt_BR/language_info
Improving language names as they appear in the phpList interface. Please check that this patch will not conflict with Pootle localisation automation / integration before merging.
> Capitalised language names; Switched Czech to use local language name

- public_html/lists/admin/viewtemplate.php
$_GET['id'] is user-controlled input, since it is not sanitized and printed directly this leads to a reflected XSS vulnerability.
$id itself is fine since the code above guarantees that it is an integer.
Fixes https://hackerone.com/reports/153799, this has been reported to the PHPList developers on July 28th. Since no further updates have been coming I decided to create a patch myself.
> Use $id instead of $_GET['id']

- public_html/lists/admin/init.php
- public_html/lists/admin/mysqli.inc
- public_html/lists/config/config_extended.php
Use mysqli_init and mysqli_real_connect instead of mysqli_connect.
Add config parameters for the port and socket, which are used by mysqli_real_connect.
> Mantis_18133 - Incorrect parameters to mysqli_connect

- public_html/lists/lt.php
Three commits
- correct the assignment of $allowPersonalised. It defaulted to false instead of true.
- remove validation of whether a campaign has been sent, as there is a scenario where a campaign can be edited after being sent and further test emails sent out. These would fail with a 404 error.
- use a regular expression to simplify the decoding of the linktrack id
> Mantis 18345 - link tracking in test messages

- public_html/lists/lt.php
Reject inputs with leading zero's as they are never used
> Tighten simplified linktrack decoding

- public_html/lists/admin/checkbouncerules.php
Headers are parsed by bounce rules, but not when you check bounces, see https://mantis.phplist.org/view.php?id=16909 for original change.
> Fix check bounce rules not matching headers

- public_html/lists/admin/processbounces.php
Avoid outputting "download failed" when there were no bounces to download.
> Mantis 18419 - Incorrect reporting when downloading no new bounces

- public_html/lists/admin/actions/processqueue.php
Also clarified two system mail subjects ("Maillist Processing info" -> "Subscriber list processing log") and added comments
> Added intro message to maillog processing email

- public_html/lists/admin/communityfeed.php
- public_html/lists/admin/onyxrss/onyx-rss.php
This has two commits. One to replace the version of onyx-rss by that used in the dressprow theme, which fixes the response-time problem.
The second commit moves the bulk of processing that is in the dressprow rssfeed.php file into core phplist. By itself it doesn't do anything, but needs the themes to include the new file in their footer.inc file
In dressprow
<div id="newsfeed" class="menutableright block">
<h3><?php echo s('phpList community news'); ?></h3>
<?php include 'communityfeed.php'; ?>
</div>
In bootstrap
<div id="newsfeed" class="menutableright block">
<h3><span class="glyphicon glyphicon-bullhorn text-danger"></span><?php echo s('phpList community news'); ?></h3>
<?php include 'communityfeed.php'; ?>
</div>
Then the rssfeed.php and onyx-rss.php files can be deleted from the …
> Mantis 18456 - bootstrap theme not using the updated community rss feed code

- public_html/lists/admin/home.php
Changes e.g. "SetupphpList" to "Setup phpList"
> Fixed missing space in anchor text

- public_html/lists/admin/EmailSender.php
- public_html/lists/admin/class.phplistmailer.php
- public_html/lists/admin/pluginlib.php
This is one part of Mantis 18294, to allow a plugin to be responsible for sending emails, instead of smtp, mail() etc.
A plugin will need to implement an interface to be recognised as being able to send emails. Similarly to the authentication plugin approach, only one plugin, the first found to implement the interface, will be selected.
The PHPlistmailer class will now use the approach shown in https://github.com/PHPMailer/PHPMailer/pull/110 so that phpmailer calls a specific method based on the value of $Mailer.
The existing code for Amazon SES and for local spool has also been changed to fit into this approach.
> Mantis 18294 Allow a plugin to be responsible for sending emails

- public_html/lists/admin/plugins.php
This change adds an explicit test for the ini setting. From the php documentation ini_get() should return a string of value either '0' or '1' for a boolean option. I have tested on three systems and that appears to be the case.
> Mantis 18503 - Clearer error message on plugins page when url fopen wrappers are not enabled

- README.md
[ci skip]
This repository no longer uses StyleCI. So the badge does not work anymore
and schould go.
> [CLEANUP] Drop the StyleCI badge from the README

- public_html/lists/admin/configure.php
On the Settings page, for a config setting of type 'select', show the label of the current item instead of the value (e.g. 'Trevelin' instead of 'phplist-ui-bootlist').
Also restructured that part of the code as a switch statement.
> Mantis 18543 - The selected theme's directory instead of its name is displayed

- public_html/lists/admin/connect.php
Handle the call to parse_ini_file failing by choosing the first theme found.
A few code fixes in the same area
- remove unnecessary trailing / from theme directory
- remove unnecessary test for duplicate entries in $THEMES
> Mantis 18569 - No theme selected when parse_ini_file has been disabled

- public_html/lists/admin/plugins.php
Minor change to make labels on the automatic plugin installation page clearer
> Added colons after plugin data labels to make separation clearer

- .travis.yml
- composer.json
- public_html/lists/admin/inc/php_compat.php
- public_html/lists/admin/index.php
As discussed in commit 452a009, I've successfully managed to keep phpList 3.3.1 working on el6 which provides only 5.3.3 via EPEL.
> Add backward compatibility support for PHP 5.3.3

- public_html/lists/admin/actions/statsoverview.php
- public_html/lists/admin/messages.php
- public_html/lists/admin/statsoverview.php
Clarifying use of 'clicks' label -- fixes inconsistent use of this label. E.g. the statsoverview page and the messages page show different statistics under the same label 'clicks'. This commit uses more descriptive labels. The longer labels take more column space/ width, which is not ideal. Improvements on space optimisation welcome.
> Clarified clicks label

- public_html/lists/admin/index.php
Currently if output buffering is enabled in php.ini then there are two levels of buffering. 
That causes progress indicators, such as when exporting, to be buffered and not displayed immediately in the browser. So instead of showing progress every 50 subscribers it is shown every 1350.
With this change, and output buffering enabled in php.ini, the progress indicator shows every 50 subscribers.
> Start output buffering selectively

- public_html/lists/admin/list.php
Existing labels are ambiguous; new labels are designed to explicitly state what the numbers show.
> Clarified labels

- public_html/lists/admin/actions/export.php
After exporting subscribers I noticed some zero length files in the temp directory.  Each time that action/export.php is run it creates a temporary file, when it needs to do that only on the first run, as the name of the temporary file is passed to the second run through the session.
There are two changes here:
- Move creation of the temporary file to avoid creating a second one.
- Reposition code dealing with the export file name.
> Avoid creating unnecessary temporary file when exporting

- public_html/lists/admin/css/app.css
- public_html/lists/admin/messages.php
Added headings to the 'list messages' table, to clarify that 'text' & 'HTML' refer to processed, not sent. Sometimes sending errors cause the 'Total' and 'HTML' totals to increase indefinitely, resulting in huge numbers. This does not indicate that messages have actually been sent however (the statistics page does that)
> Added headings to the 'list messages' page tables

- public_html/lists/admin/connect.php
Avoid trying to copy indices when copying a message.
Explicitly set the finishsending date when copying a message, otherwise eventually a repeated campaign will not be sent because finishsending is in the past.
> Mantis 18706 - Repeat message processing tries to copy an index

- public_html/lists/admin/connect.php
- public_html/lists/admin/send_core.php
@michield and @bramley please check if this change is ok for you. It will show tabs now, when there are no categories and less than 5 lists. This is the easy solution I found to the checkbox missing bug on "exclude list" accordion in both themes.
THis is the issue on github:
https://github.com/phpList/phplist3/issues/171
> Fix bug: https://mantis.phplist.org/view.php?id=18240

- public_html/lists/admin/defaultconfig.php
The whitespace removed was being rendered by mail clients and results in unexpected email formatting.
> Removed whitespace above transactional email content and at newline start

- public_html/lists/admin/actions/domainstats.php
Several sets of changes to this page to make the results more consistent:
- rework the sql as described in the mantis issue
- display confirmed, unconfirmed and blacklisted in a similar way to the lists page
- show percentages of the total number of subscribers
- round() percentages instead of truncating
- avoid repetition of the formatting of each column
- use function s() for translations
> Mantis 18437 - The domain stats page

- public_html/lists/admin/user.php
This pull request has three commits:
- add validation that an email address has been entered and does not already exist when changing the email address
- remove unused variables
- remove surrounding spaces from the entered email address
> Mantis 18729 - modifying a subscriber's email address

- public_html/lists/admin/index.php
Currently most pages have capitalised page titles but some (notably some account pages in Coipasa theme), which use this method if injecting the title, do not. This makes page titles be capitalised consistently.
> Removed application of lower case to page titles

- .gitignore
- public_html/lists/admin/help
- public_html/lists/admin/info
Packaged versions of phpList include the help and info folders within the admin directory, and this is the default location for them. However phpList 3 currently ships with symlinks pointing to above the repo root directory for these folders. This does not follow the behaviour of packaged phpList versions therefore, and also results in missing config file errors unless the Apache variable is set to give the config file path. That variable is not relevant to other web servers, and is not always set in local development environments.
Therefore this commit removes the symlinks and ensures that Git will not track the files. This makes it easier for developers to checkout the language repositories without errors.
Those wishing to use the former directory structure, with langage repo folders …
> Add translation repository folders to gitignore and remove symlinks

- public_html/lists/admin/lib.php
Initialise targetlist as an array not a string.
See https://mantis.phplist.org/view.php?id=18829
> Mantis 18829 - initialisation of targetlist

- public_html/lists/admin/inc/userlib.php
When deleting a user remove rows from user_message_forward and linktrack_uml_click tables.
Simplify the plugin processing as the default plugin provides the deleteUser() method.
> Mantis 18847 - delete from all related tables when deleting a user

- public_html/lists/admin/sendemaillib.php
There are three commits that can be reviewed individually but I can squash them into one commit:
- remove surrounding white space from an extracted url
- remove commented-out and unreachable code
- remove unused variable and redundant assignments
> Mantis 18854 Link click stores urls with trailing space

- public_html/lists/admin/index.php
When using git version and with error reporting enabled there is a php warning about developer_email being undefined.
> Avoid warning about developer_email being undefined

- public_html/lists/admin/actions/domainstats.php
- public_html/lists/admin/actions/mclicks.php
- public_html/lists/admin/actions/mviews.php
- public_html/lists/admin/actions/statsoverview.php
- public_html/lists/admin/admins.php
- public_html/lists/admin/catlists.php
- public_html/lists/admin/configure.php
- public_html/lists/admin/list.php
- public_html/lists/admin/members.php
- public_html/lists/admin/message.php
- public_html/lists/admin/mviews.php
- public_html/lists/admin/send.php
- public_html/lists/admin/spage.php
- public_html/lists/admin/statsoverview.php
- public_html/lists/admin/template.php
- public_html/lists/admin/templates.php
- public_html/lists/admin/uclicks.php
- public_html/lists/admin/userclicks.php
- public_html/lists/admin/users.php
This is answer to this mantis request:
0018788: Use standardised button layout below page heading on Subscriber lists page
Most of the changes only affect Trevelin. Only 2 changes affect Dressprow moving  buttons located at the bottom of the page to the top of the page.
I attaching images with the result of this change in Treveling. 
This commits should be merged before merge https://github.com/phpList/phplist-ui-bootlist/pull/34 in Trevelin.
> Many changes on buttons locations.

- public_html/lists/admin/mviews.php
Two translated strings already exist: responsetime and 'Response time'. This is a table heading and so we should make use of the latter.
> Replaced responsetime string with existant 'Response time'

- public_html/lists/admin/connect.php
- public_html/lists/admin/mviews.php
This limits the results shown on the mviews page from 50 to 20. Since new opens per subscriber will shortly be added, this is necessary for avoiding extremely long pages and large SQL query returns.
> Added new constant MAX_OPENS_PP and used in mviews

- public_html/lists/admin/bounces.php
I grep'd the source and the status column is always used elsewhere to hold "unidentified bounce" not the comment column.
See https://mantis.phplist.org/view.php?id=18478
> Mantis 18478 Unable to delete unidentified bounces > 2 months old

- public_html/lists/admin/admins.php
A few separate commits so that each can be reviewed individually but I can squash if necessary. 
The main change is to display more fields for each admin on the admins page. 
A second change is to allow only a super admin to delete another admin. Currently an ordinary admin is able to delete other admins, which doesn't sound right. The other changes are just tidying-up bits of the code. The commit messages should explain what each is doing.
> Display more admin fields on the admins page

- public_html/lists/admin/pluginlib.php
A few changes following investigation of a problem on a Windows server.
1) Both the constants already have fallback define's in init.php.
2) Using explode() on an empty string gives an array of one entry that is an empty string. On a Windows server I found that is_dir() on an empty string is treated as the current directory.
3) I then found that is_dir('plugins') returned true (it shouldn't as the current directory is "lists" not "lists/admin") when pluginlib.php was included from the public pages. However opendir('plugins') then failed so I suggest that the result of opendir() should be tested.
> Tidy-up usage of PLUGIN_ROOTDIRS and PLUGIN_ROOTDIR

- public_html/lists/admin/connect.php
Currently the function PageLink2() tries to get any hover text using the $name parameter, but that can include additional query parameters, e.g. importsimple&list=3, which means that the hover text is not found. 
This change is to use only the page name to get hover text.
> Get hover text using page name

- public_html/lists/admin/defaultplugin.php
- public_html/lists/admin/pluginlib.php
Currently plugins are created in an indeterminate order, and made active in that order. It will be useful to apply some control to this, so that one plugin can validly assume that another has already been activated. One example is to activate the Common Plugin first.
There are two changes:
Add priority field to a plugin.
Sort active plugins in descending priority order before activating.
> Activate plugins in a controlled order

- public_html/lists/admin/actions/listbounces.php
https://mantis.phplist.org/view.php?id=18275
>  add number formatting to total bounces  on listbounces page

- public_html/lists/admin/statsoverview.php
https://mantis.phplist.org/view.php?id=19045
- The number_format() was causing the issue
- The total views and the total clicks rows  are now displayed.
TO DO:
> Fix miscalculation of percentages on statistics overview page

- public_html/lists/admin/actions/listbounces.php
- public_html/lists/admin/index.php
- public_html/lists/admin/mviews.php
This commit is designed to get the 'total views per-subscriber' stats into the CSV export, to allow this data to be sorted. Currently it cannot be, and sorting it by default in order of total views descending in the web interface is not trivial due to the multiple queries involved.
The order of the conditionals checking for more than 1 view is used twice; once to get the total views per subscriber to include in the first table row for that subscriber, and second to add the second table row with individual view data.
This has not been tested with large data sets. A UI improvement would be to click the table row to expand and see the second table row. Also adding response time for each individual view may be beneficial for some users.
> Added 'total views' for each subscriber CSV export table

- public_html/lists/admin/mviews.php
result on dressprow:
result on trevelin:
> mantis #0018940: Reformat campaign table... on 'View opens' page

- public_html/lists/admin/inc/interfacelib.php
Testing $row['value'] for true is incorrect because it means that a value of 0 is not displayed.
But $row['value'] and $row['align'] will always have a value as they are set in the addRow() method, so there is no need to test for true or being set.
> Webbler listing row value of 0 is not displayed

- public_html/lists/admin/connect.php
php issues this warning when phplist is run from the command line
`PHP Notice:  Undefined index: ui in /home/duncan/Development/GitHub/phplist3/public_html/lists/admin/connect.php on line 133
`
> Avoid PHP warning about undefined index

- public_html/lists/admin/defaultplugin.php
- public_html/lists/admin/plugins.php
There are a few changes:
1. for plugins that have been installed from GitHub, query GitHub for the latest tag. If that is greater than the plugin's version then a new version of the plugin is available. 
Allow a plugin to provide its own method to find a new version.
3. Display the number of plugins that are enabled, disabled and have an update available
4. Reduce the number of rows displayed for each plugin by displaying two fields on one row
> Mantis 19122 check for update to plugins

- public_html/lists/admin/subscribelib2.php
Also make both email inputs use 'required' attribute
Mantis https://mantis.phplist.org/view.php?id=19168
> Make default email input field use placeholder instead of value attribute

- public_html/lists/admin/actions/export.php
- public_html/lists/admin/actions/import1.php
- public_html/lists/admin/actions/import2.php
- public_html/lists/admin/addprefix.php
- public_html/lists/admin/admin.php
- public_html/lists/admin/adminattributes.php
- public_html/lists/admin/attributes.php
- public_html/lists/admin/class.image.inc
- public_html/lists/admin/connect.php
- public_html/lists/admin/date.php
- public_html/lists/admin/dbcheck.php
- public_html/lists/admin/defaultconfig.php
- public_html/lists/admin/defaults.php
- public_html/lists/admin/editattributes.php
- public_html/lists/admin/export.php
- public_html/lists/admin/import1.php
- public_html/lists/admin/import2.php
- public_html/lists/admin/import3.php
- public_html/lists/admin/importadmin.php
- public_html/lists/admin/inc/importlib.php
- public_html/lists/admin/inc/userlib.php
- public_html/lists/admin/initialise.php
- public_html/lists/admin/mysqli.inc
- public_html/lists/admin/sendprepared.php
- public_html/lists/admin/spageedit.php
- public_html/lists/admin/stresstest.php
- public_html/lists/admin/subscribelib2.php
- public_html/lists/admin/template.php
- public_html/lists/admin/upgrade.php
- public_html/lists/admin/user.php
Replace `while (list($key, $value)  = each(...))` by an equivalent foreach() construct.
There was one instance of list($key) instead of list($key, $value) in template.php but that processing has been simplified by avoiding it completely.
> Mantis 19178 - In php 7.2 the each() function is deprecated

- README.md
Missing "i" in personalisation:
personalisaton -> personalisation
> README.md: fix "personalisaton" typo

- public_html/lists/admin/actions/reconcileusers.php
- public_html/lists/admin/connect.php
- public_html/lists/admin/inc/userlib.php
- public_html/lists/admin/pageaction.php
- public_html/lists/admin/reconcileusers.php
Two buttons added to Reconcile Subscribers page:
- Delete subscribers who are blacklisted because they unsubscribed
- Delete all blacklisted subscribers
Also adds and uses new functions for deleting subscribers, including all related blacklist data (in blacklist-related database tables).
https://mantis.phplist.org/view.php?id=19221
> Add buttons to delete all blacklisted subscribers

- public_html/lists/index.php
https://mantis.phplist.org/view.php?id=19232
Adds a 'Contact the administrator' link to the public homepage (/lists) to make it easier for subscribers to request copies of their data, rectify or erase it.
Uses simple email HTML entities-based email address obfuscation.
> Added link to contact the administrator on public homepage

- public_html/lists/admin/init.php
- public_html/lists/config/config_extended.php
- public_html/lists/index.php
https://mantis.phplist.org/view.php?id=19228
This adds a link to the generic public preferences page from the default homepage of the phpList installation. E.g. alongside the existing links from /lists to the default subscribe page and default unsubscribe pages, a link to the preferences page (which takes either the subscriber UID or their email address to send them their personal link) is included.
This is to make it easier for subscribers to manage their preferences even if they do not have a campaign link available.
> Add preferences link to /lists homepage

- public_html/lists/admin/mviews.php
> #19209: Horizontally align 'Campaign statistics' button on 'View opens"

- public_html/lists/admin/lib.php
> Use correct column name of message table  on resetMessageStatistics

- public_html/lists/admin/message.php
- public_html/lists/admin/messages.php
Display the names of the lists to which a campaign has been or will be sent.
I have added a row to show the list names but there might be a better way of doing that. To avoid the "Lists" label, maybe append the list names to the campaign subject
> Display list names on the messages page

- public_html/lists/admin/languages.php
This function is useful for escaping translation content.
> Create htmlentities version of s function 

- public_html/lists/admin/send_core.php
The text message in the editor was not properly encoded, when the data was rendered a second time (and edited) this resulted in the browser transmitting HTML special characters instead of the encoded versions. Thus breaking stuff that relied on special characters such as URLs containing `&curren`.
To reproduce this:
1. Enable the manual text editor (define('USE_MANUAL_TEXT_PART',1);)
2. Enter the following message as text: "https://www.paypal.com/cgi-bin/webscr?business=hbeer@ability1group.eu&cmd=_donations&amount=0&item_name=DEEPclearing&lc=en_US&currency_code=DKK"3. Go to the next section
4. Go back to "Text" and see it broken (since it's double encoded)
Fixes https://discuss.phplist.org/t/url-for-paypal-donation-destroyed-in-text-message-window/3517
Signed-off-by: Xheni Myrtaj …
> Encode text message in editor

- public_html/lists/admin/messages.php
The request comes up every now and then for the ability to copy a previously sent message into draft.
This adds a button in the "Sent" campaign list to do so.
https://forums.phplist.com/viewtopic.php?p=39364
Updated the patch to work with the latest version.
Would be nice if this could be coded as a plugin, but there isn't a hook for it yet.
https://mantis.phplist.org/view.php?id=19263
> Copy to draft feature

- public_html/lists/admin/sendemaillib.php
Correct misspelt variable name that stopped a plugin adding an attachment to an email.
Can this be added to the pending 3.3.4 release in addition to master?
> Plugin adding attachments does not work

- public_html/lists/admin/initialise.php
- public_html/lists/admin/lib.php
> Set ownerid of invite campaign to 1 for fresh new installations

- public_html/lists/admin/pluginlib.php
There is a problem when a plugin is updated and then does not meet its dependencies.
On the Plugins page it is correctly shown as disabled due to dependency checks, but the processing in pluginlib.php, on each page load, treats it as still being enabled and the plugin's menu items etc are still displayed. Depending on what the dependencies actually are, this can cause a failure that can be difficult to diagnose.
This change adds a test of whether each plugin can be enabled and ignores plugins that are already enabled but fail the test.
> Do not enable a plugin that does not meet its dependencies

- public_html/lists/admin/actions/import1.php
- public_html/lists/admin/actions/import2.php
- public_html/lists/admin/importsimple.php
- public_html/lists/admin/members.php
Use "insert ignore" instead of "replace into" when adding records to the listuser table.
For simple import, count insertions in the same way as for import1 and import2.
On the list membership page, make all the options count insertions in the same way, and ensure that the entered field is populated.
> Mantis 19403 - Use of mysql "replace into" with the listuser table

- public_html/lists/admin/actions/msgbounces.php
- public_html/lists/admin/bouncemgt.php
- public_html/lists/admin/connect.php
- public_html/lists/admin/locale/en/pagetitles.php
- public_html/lists/admin/msgbounces.php
> Display bounces per campaign

- public_html/lists/admin/lib.php
This is a quick fix for Mantis 17649 https://mantis.phplist.org/view.php?id=17649
The problem is that, when trying to remove some specific query parameters from a url, the url can get changed or corrupted. The current processing breaks a url into its constituent parts then reassembles those, even when there is no need for that.
This change is simply to leave alone urls that do not contain any of the disallowed parameters.
A better, but larger, solution is to rework and simplify the processing of urls for link tracking.
> Mantis 17649 Click tracking decoding urlencoded characters

- public_html/lists/admin/pluginlib.php
Move the test of whether a plugin can be enabled to where all plugins have been created.
> Mantis 19453 - Some plugins were disabled after upgrading to release 3.3.5

- public_html/lists/admin/inc/maillib.php
Still removes "#anchor" but not "https://www.exameple.com/#anchor".
> Don’t remove useful anchor links

- public_html/lists/admin/defaultconfig.php
- public_html/lists/admin/spageedit.php
- public_html/lists/admin/subscribelib2.php
-https://github.com/phpList/phplist-ui-bootlist/pull/74 needs to be merged for lists to be split into two columns.
> Group lists by category feature 

- public_html/lists/admin/actions/import2.php
- public_html/lists/admin/import2.php
The current processing strips any double-quotes then splits on the field separator.
The str_getcsv() function recognises fields wrapped in double quotes and allows the field separator to appear in the field value.
> Mantis 19542 - Allow import of attribute value that includes a field separator

- public_html/lists/admin/inc/maillib.php
- public_html/lists/admin/sendemaillib.php
Ensure matching delimiter when processing href attribute in three places
- finding links in an html format message for click tracking
- finding links to add google tracking
- converting an html format message to plain text
> Mantis 19555 - URL is truncated when click tracking is enabled

- public_html/lists/admin/index.php
Correct the test to issue warning for incorrect $pageroot.
The warning is now displayed when the current request does not begin with $pageroot followed by '/admin'. For example $pageroot has default value of '/lists' but phplist has been installed in '/newsletter'.
> Warning not issued for incorrect $pageroot

- public_html/lists/admin/defaultplugin.php
- public_html/lists/admin/index.php
Allow a plugin to have pages that can be accessed using the remote processing secret.
1) Add an array of remote pages to the default plugin.
2) Test that when the secret parameter is provided and the current page is for a plugin that the page is in the array of remote pages provided by the plugin.
3) set $inRemoteCall accordingly
> Plugin remote pages

- public_html/lists/admin/connect.php
Convert only the numeric part of the php memory limit to avoid php issuing a notice 
`PHP Notice:  A non well formed numeric value encountered in /home/duncan/Development/GitHub/phplist3/public_html/lists/admin/connect.php on line 1514, referer: http://strontian/lists/?p=forward&mid=103&uid=1bbf5b37bbb1df69698c4b89e1429474`
> Avoid php notice when converting php memory limit

- public_html/lists/admin/actions/processqueue.php
Avoid php notice re undefined index when sending is blocked by a plugin
`[Wed Nov 28 12:39:35.992842 2018] [php7:notice] [pid 2323] [client 127.0.0.1:45052] PHP Notice:  Undefined index: send blocked by Segmentation in /home/duncan/Development/GitHub/phplist3/public_html/lists/admin/actions/processqueue.php on line 1060`
> Avoid php notice re undefined index

- public_html/lists/admin/spageedit.php
An earlier change https://github.com/phpList/phplist3/pull/348 didn't include the sections for plugins, which are now displayed before other sections.
This change is to display any plugin sections at the end.
> When editing a subscribe page display the plugin section at the end

- public_html/lists/admin/connect.php
- public_html/lists/admin/index.php
- public_html/lists/admin/init.php
- public_html/lists/admin/redirecttoupdater.php
- public_html/lists/config/config_extended.php
Mantis: https://mantis.phplist.org/view.php?id=19654
> Add option to disable the automatic updater

- public_html/lists/admin/connect.php
- public_html/lists/admin/convertstats.php
- public_html/lists/admin/cron.php
- public_html/lists/admin/import.php
- public_html/lists/admin/index.php
- public_html/lists/admin/initlanguages.php
- public_html/lists/admin/processbounces.php
- public_html/lists/admin/processqueue.php
- public_html/lists/admin/send.php
- public_html/lists/admin/updatetlds.php
- public_html/lists/admin/upgrade.php
Output the command line signature in only one place in index.php, allowing all other calls to ClineSignature() to be removed
```
before for page initlanguages
======
phpList - phpList version 3.3.7 (c) 2000-2018 phpList Ltd, https://www.phplist.com
Try automatic updater here (beta)
phpList version 3.3.7 (c) 2000-2018 phpList Ltd, https://www.phplist.comphpList - pt
phpList - Up to date
phpList - de
phpList - Up to date
after
=====
phpList - phpList version 3.3.7-dev (c) 2000-2018 phpList Ltd, https://www.phplist.com
Running DEV version, but developer email is not set
phpList - pt
phpList - Up to date
phpList - de
phpList - Up to date
```
> Mantis 19347 - command line signature is displayed twice

- public_html/lists/admin/actions/bounces.php
- public_html/lists/admin/actions/mviews.php
- public_html/lists/admin/actions/statsoverview.php
- public_html/lists/admin/uclicks.php
- public_html/lists/admin/userclicks.php
Most dates are formatted in php, which allows translation of the month name. This PR fixes a few dates that were formatted in sql.
> Mantis 19611 - some dates have month in English

- public_html/lists/config/config_extended.php
A previous change #443 causes a warning to be shown when phplist is installed in the web root directory and $pageroot is set to '/' instead of an empty string, ''. That has always been incorrect as it causes double '/' characters in some URLs constructed by phplist.
My editor has also removed trailing spaces from some other lines.
> Clarify $pageroot when phplist is installed in the web root directory

- public_html/lists/admin/actions/processqueue.php
- public_html/lists/admin/processbounces.php
As discussed in #440 the validation of the remote processing secret is duplicated. This PR has four parts
- removes the validation from processbounces
- removes the validation from processqueue
- allows remote processing for processbounces when MANUALLY_PROCESS_BOUNCES is set to false (which makes it similar to processqueue and MANUALLY_PROCESS_QUEUE). The benefit is that process bounces is removed from the admin interface.
- makes the output of processbounces with remote processing simpler by outputting only text, not html. So the output is then similar to that for command line.
I have tested these changes using remote processing, but not with processing the queue by the phplist hosted service. That doesn't appear to be running or at least is not responding to my account.
> Remote processing validation

- public_html/lists/admin/send_core.php
When using the Firefox web console tool to see what was sent when submitting a campaign I noticed that two hidden fields were duplicated, the message id and the message status. This change removes those.
> Repeated html input fields on the Send a Campaign page

- public_html/lists/admin/messages.php
This change covers some of the points raised in the mantis issue
- display the actual sort order when the page is displayed for the first time
- allow each tab to have its own sort order, which is remembered throughout the session
Also, there is some restructuring to hold all tab related fields and all sort-order related fields in structures instead of being spread throughout the code.
I think that there is still a usability issue allowing sorting by a field whose value is not displayed (such as the embargo), but maybe that can be addressed separately. This change doesn't affect that.
> Mantis 18435 - sort order on the List Campaigns page

- public_html/lists/admin/admin.php
I found weird behaviour when trying to send the password reset email on the Admin page.
The confirmation message didn't say that the email had been sent, but after a further change to an admin field it did say that.
An earlier change https://github.com/phpList/phplist3/pull/399/files#diff-151b5aaf0a8d1c46203a572c46ab3746L193 re-ordered the radio button captions from No then Yes to Yes then No but didn't modify the html attribute values, which meant elsewhere checks for Yes are being met when the No button is selected.
> Correct the values for the updatepassword radio buttons.

- public_html/lists/admin/lib.php
Remove erroneous space from the CONTACT url
Allow lower case CONTACT placeholder to be used, similarly to other phplist placeholders.
https://mantis.phplist.org/view.php?id=19794
> Mantis 19794 - CONTACT placeholder not replaced correctly

- public_html/lists/admin/subscribelib2.php
Ensure that lists are ordered by the list order field when displayed within categories.
There are also a few removals of trailing white space, which is done automatically by my editor.
https://mantis.phplist.org/view.php?id=19792
The specified list order
Subscribe page prior to the change
Subscribe page after the change
> Mantis 19792 - Subscriber page ignores list order if categories are used

- public_html/lists/admin/defaultconfig.php
- public_html/lists/admin/home.php
- public_html/lists/admin/index.php
- public_html/lists/admin/initialise.php
- public_html/lists/admin/updateLib.php
- public_html/lists/admin/upgrade.php
Done
https://mantis.phplist.org/view.php?id=19760
TODO
> Introduce new notification for updates

- public_html/lists/admin/defaultsystemtemplate.php
Add license and attribution info for recently added email template
[Mantis](https://mantis.phplist.org) : https://mantis.phplist.org/view.php?id=19820
> Add credit and license in docblock for 3rd party email template

- public_html/lists/admin/sendemaillib.php
This fixes a problem when forwarding a message that has a custom forward footer. The forwarded message does not include the footer due to the code  using an incorrect/non-existent variable.
See https://discuss.phplist.org/t/missing-footer-when-forwarding-to-a-friend/4696/8 for the discussion.
[Mantis](https://mantis.phplist.org) :
Prior to the change, the email does not have the footer
After the change, the email now does include the footer
> Use the correct variable for the custom forward footer when forwarding

- public_html/lists/admin/defaultsystemtemplate.php
System template should be checked as "system" by default when loaded. Fixed the title name that caused the issue.
https://mantis.phplist.org/view.php?id=19866
> Fix system template title name 

- public_html/lists/admin/index.php
https://mantis.phplist.org/view.php?id=19837
> Check for required PHP extensions

- README.md
Update the Readme file on phpList3 repo to state other repos needed in the development copy.
Mantis : https://mantis.phplist.org/view.php?id=19844
> Edit readme file to state other repos for phpList development copy

- public_html/lists/.htaccess
- public_html/lists/api.php
Added api.php in lists which is needed to create shorters API calls.
The new base url will be : http://example.com/lists/api.php/
Example: http://example.com/lists/api.php/sessions
Will push changes to core repo too.
To do: Fix the tests. Remove  strict_types as it's not supported in old versions of PHP and add a PHP version check.
https://mantis.phplist.org/view.php?id=19847
> Shorten API calls

- public_html/lists/admin/upgrade.php
Fix https://mantis.phplist.org/view.php?id=19867
> Update jQuery version of default public page and other subscribe pages

- public_html/lists/admin/upgrade.php
Update footer of users that upgrade from 3.4.0 to 3.4.1, to prevent having blank subscribe pages due to "not found" file of jQuery.
> Public page footer Update for v3.4.0

- public_html/lists/admin/templates.php
- Add explicit edit button for each template to the 'list templates' page
- Move edit buttons to same line, right side
- Remove unnecessary ID column
- Change table title
- Add unique title for first column
[Mantis](https://mantis.phplist.org) :
> Improvements to List Templates page

- public_html/lists/admin/import2.php
Fix https://mantis.phplist.org/view.php?id=19862
> Make "Omit Invalid" option checked by default on  CSV import page

- public_html/lists/admin/actions/import1.php
- public_html/lists/admin/import1.php
1. Email validation on "import via a text file" (used "is_email" function)
2. Added "Count invalid emails" to import report
3. Validate emails only if "omit invalid" is checked (it's checked by default)
https://mantis.phplist.org/view.php?id=19861
> Add email validation on import via txt file

- public_html/lists/dl.php
Added support for inline attachments like PDF files
https://mantis.phplist.org/view.php?id=15277
> Support for inline attachments

- public_html/lists/admin/index.php
- public_html/lists/admin/updateLib.php
- Return false if a production version is not found. 
- Updated PHPDocs.
- Show notification only if the version is found in init.php.
- Check if curl extension is loaded before checking for update.
TBA
> Improve notification logic

- tests/features/bootstrap/FeatureContext.php
- tests/features/getting-started/publicPages.feature
This is a simple test that looks for the default links on the public pages and checks if they lead to the corresponding pages.
Mantis: https://mantis.phplist.org/view.php?id=19925
> Test links in public pages

- public_html/lists/admin/sessionlib.php
Fix 500 Error with no error message under PHP 7.2 and make MySQL session handler work.
- Tested to work with PHP 7.2 and 5.6
- ini_set('session.save_handler', 'user') not allowed in php 7.2
- The read callback must always return a session encoded (serialized) string, or an EMPTY STRING if there is no data to read.
> Make MySQL Sessions work with PHP 7.2

- public_html/lists/admin/subscribelib2.php
$_REQUEST['email'] and $_REQUEST['emailconfirm'] are already allowed, so let's also support the other two fields.
https://mantis.phplist.org/view.php?id=15235
> Accept $_GET parameters &list=x,y,z (or just &list=x) and &htmlemail=1

- public_html/lists/admin/export.php
This JS is not needed and causes an error as it runs before jQuery is loaded. 
The functionality is handled in admin/js/phplistapp.js around line 395
NA
error from chrome
?page=export&tk=2cfda4e7e6cba9534ba3bdaec27d651a:289 Uncaught ReferenceError: $ is not defined
> redundant JS causing error

- public_html/lists/admin/dbcheck.php
Remove duplicate page title on verify db structure page
https://mantis.phplist.org/view.php?id=19894
> Remove duplicate page title on verify db structure page

- public_html/lists/admin/send.php
An sql syntax error was reported when running the send page from the command line
```
phpList - Database error 1064 while doing query  You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '' at line 1
phpList - Sql error SELECT * FROM phplist_message where id = 148  and owner = 
```
This was caused by incorrect permissions being derived when phplist is run from the command line. There are two changes
1) The function accessLevel() returns 0 as a default value when the an admin is not logged-in.  The usual way of the calling code testing this value is through a switch statement with cases such as 'owner' or 'all'. But those comparisons are "loose" which means 0 will match the first case, usually 'owner', …
> Send sql error

- public_html/lists/admin/processbounces.php
Will do some additional testing before it's ready to review.
https://mantis.phplist.org/view.php?id=18078
>  Time of bounce in history of a subscriber profile

- public_html/lists/admin/spageedit.php
Escape $title value in insert query.
TBA
> Escape title value in edit subscribe page

- public_html/lists/admin/defaultconfig.php
Corrected two typos on the footer. 
Mantis:  https://mantis.phplist.org/view.php?id=19942
> corrected two typos on the footer

- public_html/lists/admin/connect.php
- public_html/lists/admin/subscribelib2.php
There was no check if the list is private or not when users subscribe/update preferences.
I created a function that determines if the list is private or not. Additional test is needed.
TBA
> Prevent subscribing to private lists

- public_html/lists/admin/upgrade.php
Reset maintenance mode when running the upgrade script and no upgrade is necessary
https://mantis.phplist.org/view.php?id=19972
> clear Maintenance mode if there's no need to upgrade

- public_html/lists/admin/plugins.php
Ensure that regex pattern is compatible with php 7.3
https://mantis.phplist.org/view.php?id=20004
> Updating a plugin fails due to php 7.3 PCRE change

- public_html/lists/admin/js/phplistapp.js
https://mantis.phplist.org/view.php?id=19998#bugnotes
https://mantis.phplist.org/view.php?id=19994#bugnotes
> Replacement of id attribute with name in checkAllBoxes function-campaigns sending

- public_html/lists/admin/send_core.php
When inserting into message table fails return to the caller instead of exiting, which is the same approach as used elsewhere.
https://mantis.phplist.org/view.php?id=20028
Trevellin now displays the error
Dressprow displays the error
> Mantis 20028 - When insert into message table fails the fatal error is not displayed by Trevellin theme

- .travis.yml
Not sure why travis is now using xenial on the build set up so, a simple PR from @marianaballa is failing the checks: https://travis-ci.org/phpList/phplist3/builds/563051547
> add trusty for the build dist

- public_html/lists/admin/exportuserdata.php
Use the config file's centrally set csv delimiter (set via EXPORT_EXCEL) instead of always comma. Makes the exported user data use tab delimiter by default. Improves consistency of csv formatting across exports.
> Check for and use the centrally set csv delimiter instead of comma

- public_html/lists/admin/exportuserdata.php
- public_html/lists/admin/userclicks.php
Data in the csv table 'User clicks Info' was missing due to the db query used. Replace the sql query to get data, and more data.
Also add a check for the forwarded email data to see if any results are returned, and if not, print message saying so.
Note: The behaviour of tables where no data is found is now inconsistent: all tables show col headings and no data, except for the forwarded message data table, which now does the table title and a message stating forwarded data is absent of that is the case. It would be good to add conditional checks to the other tables to test for this too in future.
> Fix more detailed subscriber click stats the userdataexport csv files

- public_html/lists/admin/processbounces.php
Improve matching of email addresses within a bounce.
The change uses the same regex as when parsing a plain text campaign email to find email addresses, function parseText() in sendemaillib.php.
https://mantis.phplist.org/view.php?id=20037
> Mantis 20037 - Failing to identify the email address in a bounce

- public_html/lists/admin/connect.php
Add website config option value to the stats email which is sent after a campaign finishes sending.
> Add website config option to stats recorded

- public_html/lists/admin/connect.php
When displaying a set of results using simple paging
- Avoid paging past the final page.
- Display only the remaining items on the last page.
https://mantis.phplist.org/view.php?id=20069
Event log page showing the last page,
prior to change shows the last 50 events
after change shows the last 47 events
> Mantis 20069 - Some quirks with simple paging

- public_html/lists/admin/CsvReader.php
- public_html/lists/admin/actions/import2.php
- public_html/lists/admin/import2.php
- tests/phpunit/CsvReaderTest.php
Use fgetcsv() to parse an import file. Instigated by discussion on another pull request https://github.com/phpList/phplist3/pull/585
New class to encapsulate reading a csv file. It uses fgetcsv() to read line by line instead of loading the complete file into an array. This is to reduce the memory usage but requires the file to be parsed twice in order to count the number of rows.
Similar changes to admin/import2.php and admin/actions/import2.php to use the new class.
Remove references to the $email_list variable.
Remove the current manipulation of the various line endings.
Use htmlspecialchars() instead of addslashes()
Some phpunit tests.
https://mantis.phplist.org/view.php?id=19934
> Mantis 19934 - Parse CSV by CSV standard - rfc4180

- public_html/lists/admin/processbounces.php
Add missing quotes around datetime value when inserting into the user_message_bounce table.
> Mantis 20117 - processbounces has sql error inserting into user_message_bounce table

- public_html/lists/admin/actions/campaigns.php
On the Campaigns tab of the Subscriber Profile page
- display the campaign title instead of the campaign id, as that should be more useful.
- when the email bounced display the time of the bounce. This used to be displayed but an earlier change to the tabs stopped it working.
- ensure that the viewed and response time columns are always displayed so that the bounce column is displayed after those. The bounce column will be displayed only when at least one email has bounced.
> Display campaign title and bounce time on Subscriber Profile campaigns tab

- public_html/lists/admin/converttoutf8.php
- public_html/lists/admin/upgrade.php
Two changes to the page that converts the database to UTF8.
- Avoid displaying the warning about lack of disk space when the database has already been upgraded to UTF8. Displaying the warning regardless had caused some confusion, see this topic in the user forum https://discuss.phplist.org/t/is-there-a-way-to-convert-database-to-utf8-by-command-line/5732/10
- Currently the processing checks the space available on the drive with the root directory '/', which might not be the actual location of the database. mysql has a parameter, datadir, giving the location of the database that can be used instead of '/'.
This change is also made to the upgrade page.
> Converting the database to UTF8

- public_html/lists/admin/sendemaillib.php
Looking at an email that was sent from Mailchimp there was a List-Unsubscribe-Post header that I had not noticed previously.
```
List-Unsubscribe: <https://ianvisits.us19.list-manage.com/unsubscribe?u=7c0eed00da5d863f228529675&id=1c15e553b2&e=ceacaa0bc4&c=3aed3f5a59>, <mailto:unsubscribe-mc.us19_7c0eed00da5d863f228529675.3aed3f5a59-ceacaa0bc4@mailin.mcsv.net?subject=unsubscribe>
List-Unsubscribe-Post: List-Unsubscribe=One-Click
```
The purpose of that header, explained in https://tools.ietf.org/html/rfc8058, is to provide a signal that the List-Unsubscribe header field has one-click functionality, which phplist does have because of the `jo` parameter. An example
```
List-Unsubscribe: <http://strontian/lists/?p=unsubscribe&uid=1bbf5b37bbb1df69698c4b89e1429474&jo=1>
```
Adding this header …
> Include List-Unsubscribe-Post header to indicate one-click functionality

- public_html/lists/admin/processbounces.php
When inserting into the bounce table the date column is taken from the Date header of the bounce but the value does not include seconds. See screenshot where all date column values have 0 seconds.
This change makes the value include the seconds value from the Date header. The phplist code has been like this for years, so there might have been a reason for not including seconds but I can't see that is important now.
> Include the seconds value in the date field of a bounce record.

- public_html/lists/admin/class.phplistmailer.php
- public_html/lists/admin/sendemaillib.php
Simplify the use of the phpmailer addCustomHeader() method to avoid unnecessary joining of the header name and header value. phpmailer immediately converts that back to header name and header value.
Remove some redundant methods:
- build_message() is not used anywhere in the phplist code
- CreateBody() overrides the parent method but now doesn't add anything
- Send() also overrides the parent method but doesn't add anything and doesn't appear to be called from anywhere
Remove unused parameters $headers and $envelope from compatSend().
Headers in an email after the changes
> Tidy-up some code in phplistmailer

- public_html/lists/admin/send_core.php
It fixes this issue in mantis: https://mantis.phplist.org/view.php?id=20139
> remove duplicated 'select one' option, capitalize it

- public_html/lists/admin/messages.php
On the List of Campaigns page the number of bounces for a campaign is a link to the wrong page. Currently it goes to the bounces page but should go to the msgbounces page which shows bounces only for that campaign.
> Correct the target page to show bounces for a campaign

- public_html/lists/admin/msgbounces.php
The message bounces page has one row for each bounce for that campaign, but the rows do not show or link to the actual bounce. The rows also have two links to the subscriber page.
This change includes the bounce id as a link to the bounce page.
Prior
After
> On the message bounces page display the bounce id

- public_html/lists/admin/mclicks.php
Make the total clicks value consistent between the Campaign click statistics summary page and the detailed page for a specific campaign.
https://mantis.phplist.org/view.php?id=20150
The Summary page shows 116 clicks
But the detailed page for the campaign shows 69 clicks.
After this change the two figures are the same
> Mantis 20150 - Total Clicks on campaign list page reports error

- public_html/lists/admin/class.phplistmailerbase.php
- public_html/lists/config/config_extended.php
Allow PHPMAILER_PATH to specify a different version of PHPMailer 6 to simplify testing a later version of PHPMailer.
> Allow PHPMAILER_PATH to specify a different version of PHPMailer 6.

- public_html/lists/admin/inc/maillib.php
A problem raised on the user forum regarding a link whose URL was a phone number, tel:1234, being changed to an http URL
https://discuss.phplist.org/t/problems-with-href-links/2026/9
When adding absolute resources leave alone URLs that already have a scheme. The regular expression allows any valid scheme as described at https://www.ietf.org/rfc/rfc2396.txt section 3.1.
> Do not change URLs that already have a scheme

- public_html/lists/config/config_extended.php
In config_extended.php the link to the PHPMailer documentation is outdated.
> Correct the link to the PHPMailer documentation

- public_html/lists/admin/AnalyticsQuery.php
- public_html/lists/admin/analytics.php
- public_html/lists/admin/defaultconfig.php
- public_html/lists/admin/js/phplistapp.js
- public_html/lists/admin/pluginlib.php
- public_html/lists/admin/send_core.php
- public_html/lists/admin/sendemaillib.php
- public_html/lists/lt.php
- tests/phpunit/AnalyticsTest.php
Add Matomo as an alternative to Google Analytics. When selected each URL will have four additional query parameters that are similar to the existing Google Analytics parameters
Google
utm_source - set to 'phpList'
utm_medium - set to 'email'
utm_campaign - set to the campaign subject
utm_content - set to either HTML or text depending on the email format
Matomo
pk_source - set to 'phpList'
pk_medium - set to 'email'
pk_campaign - set to the campaign subject
pk_content - set to either HTML or text depending on the email format
Additionally, the parameters will be displayed and can be edited on the Finish tab when composing a campaign.
The approach is to have a class for Google Analytics that provides the appropriate query parameters. Similary for Matomo. Additionally a plugin can implement …
> Add support for including Matomo instead of Google Analytics query parameters on URLs

- public_html/lists/admin/connect.php
- public_html/lists/admin/defaultconfig.php
Provide a configuration setting to allow customising the format of a displayed date.
The functions dealing with formatting dates and times have been moved to be together.
Currently some pages such as Statistics Overview force the month to be displayed in short format. This change does not change that.
The time part of a datetime is not changed by this.
Configure to display the month name first
Resultant display of a date
Help text
> Format dates using a configurable format string

- public_html/lists/admin/admin.php
- public_html/lists/admin/plugins.php
- public_html/lists/admin/send.php
Use consistent formatting of date and datetime fields on the Send, Admin and Plugins pages.
On the admin page use a switch statement to help clarify the processing.
Send a campaign page before the change
After the change
> Use the standard processing to format some datetime values.

- public_html/lists/admin/connect.php
The specifier 'n' to format a month without leading 0 should have been included in the original change, #639
> Add 'n' specifier to format month without leading 0.

- .travis.yml
Dpkg was failing to download the latest version of Chrome so, this re-installs dpkg, removes the addons section and uses wget to install the stable version of chrome.
> Travis setup fixes

- public_html/lists/admin/PEAR/HTTP/Request2.php
- public_html/lists/admin/PEAR/HTTP/Request2/Adapter.php
- public_html/lists/admin/PEAR/HTTP/Request2/Adapter/Curl.php
- public_html/lists/admin/PEAR/HTTP/Request2/Adapter/Mock.php
- public_html/lists/admin/PEAR/HTTP/Request2/Adapter/Socket.php
- public_html/lists/admin/PEAR/HTTP/Request2/CookieJar.php
- public_html/lists/admin/PEAR/HTTP/Request2/Exception.php
- public_html/lists/admin/PEAR/HTTP/Request2/MultipartBody.php
- public_html/lists/admin/PEAR/HTTP/Request2/Observer/Log.php
- public_html/lists/admin/PEAR/HTTP/Request2/Observer/UncompressingDownload.php
- public_html/lists/admin/PEAR/HTTP/Request2/Response.php
- public_html/lists/admin/PEAR/HTTP/Request2/SOCKS5.php
- public_html/lists/admin/PEAR/HTTP/Request2/SocketWrapper.php
- public_html/lists/admin/PEAR/Net/URL2.php
- public_html/lists/admin/PEAR/PEAR/Exception.php
- public_html/lists/admin/actions/updatetranslation.php
- public_html/lists/admin/index.php
- public_html/lists/admin/init.php
- public_html/lists/admin/lib.php
- public_html/lists/admin/plugins.php
Add HTTP_Request2 as a fallback when curl is not available. This means that phplist will always be able access URLs for functions such as
- retrieving a web page as the content of a campaign
- validating remote images in a template
- installing plugins
- updating translations
Currently these depend on one of curl being available or http wrappers being enabled.
This change has been tested with php 5.6 and php 7.
The first commit adds the PEAR package HTTP_Request2 and its dependencies.
The second commit comprises
1. in init.php
add the PEAR subdirectory to the include path
set global $can_fetchUrl to always be true
2. in lib.php
- amend function testUrl() to use HTTP_Request2 when curl is not available
- add time-to-live parameter to fetchUrl() to allow the timeout value to vary
- add …
> Use PEAR package HTTP_Request2 as fallback

- public_html/lists/admin/defaultconfig.php
Adds an info icon for the website field.
https://mantis.phplist.org/view.php?id=20185
Related to https://github.com/phpList/phplist-lan-help/pull/24
> Add popup help for the website field on the Settings page

- public_html/lists/admin/uclicks.php
Make the link clickable at the top of the click stats page; particularly useful when the links in question are obfuscated or do not communicate the content they relate to (eg tweets).
> Link the link to the actual URL destination for convenience

- public_html/lists/admin/uclicks.php
Add link escaping that should have been previously present for the link in the page heading, and should have also been included in #656. Thanks to @bramley.
> Add link escaping

- public_html/lists/admin/admin.php
- public_html/lists/admin/admins.php
Fix #660 and fix other XSS that are in /admin and /admins.
The admin could inject malicious code in the loginname field and also via the admin attribute name.
To replicate the admin attribute one - > go to /adminattributes page-> add a new attribute-> set the attribute name to `<script>alert(1)</script>` and then go to /admin.
The issue is fixed by using `htmlentities` when outputting user-controlled data.
> Use htmlentities to output user controlled data in admin and admins pages

- public_html/lists/admin/actions/generatetextpreview.php
- public_html/lists/admin/send_core.php
~All popular mobile mail clients include a preview of email content as well as the subject line. This is [common functionality](https://sendgrid.com/blog/perfecting-your-email-preview-text/) among other ESPs.
The text preview is currently hard to know using phpList unless you send a test message. Mail clients read the plaintext version of the message and take the first 35-90 chars for preview. In phpList the 'text' tab is optional, and often disabled. In such cases it's not possible to know the mail client preview before sending the campaign (when plaintext version is presumably generated at queue processing time).
Therefore this PR adds a message preview to the html campaign composer page (content tab). It has simple logic, using the existing backend functions for retrieving saved …
> Add new message preview field to campaign composer for mail client previews

- public_html/lists/admin/index.php
- public_html/lists/admin/init.php
When phplist is installed in the web root directory, instead of '/lists', $pageroot should be set to an empty string otherwise there is a warning about it not being correct. Despite being explained in config_extended.php there is still a recurring problem of $pageroot being set to '/'.
It is probably simplest just to silently change a value of '/' to an empty string.
Also improve the warning message by including the values that do not match.
> Avoid possible warning about $pageroot when phplist is installed in the web root

- public_html/lists/admin/actions/checkurl.php
- public_html/lists/admin/actions/storemessage.php
- public_html/lists/admin/init.php
- public_html/lists/admin/lib.php
- public_html/lists/admin/send_core.php
- public_html/lists/admin/sendemaillib.php
- public_html/lists/admin/template.php
The use of the PEAR HTTP_Request2 package as a fall-back when curl is not available means that phplist is always able to retrieve remote URLs. This change tidies-up some code that is now redundant:
- Remove uses of $can_fetchUrl which is now always true.
- Remove function fetchUrlPear() which is not used.
> Remove redundant code now that phplist can always retrieve remote URLs

- public_html/lists/admin/spageedit.php
The admin name should be htmlescaped on output. 
To replicate the XSS issue:  
Create an admin where login name is` <script>alert(1)</script>` and go to edit a subscribe page. The javascript will be fired.
> Use htmlentities to output the admin name on subscribe page

- public_html/lists/admin/editlist.php
The admin name should be htmlescaped on output.
To replicate the XSS issue:
Create an admin where login name is <script>alert(1)</script> and go to "edit a list" page. The javascript will be fired.
> Use htmlentities to output the admin name on the edit list page

- public_html/lists/config/config_extended.php
The current configuration(`config_extend.php`) describe the following.
This description is incorrect. The correct value is 1.
I wrote the detail #687
> Click track, list detail
> if you enable this, you will get some extra statistics about unique users who have clicked the
> links in your messages, and the breakdown between clicks from text or html messages.
> However, this will slow down the process to view the statistics, so it is
> recommended to leave it off, but if you're very curious, you can enable it
This change fixes #687 issue.
> Fix Incorrect CLICKTRACK description(Wrong default value).

- public_html/lists/admin/defaultFrontendTexts.php
- public_html/lists/admin/sendemaillib.php
- public_html/lists/index.php
When forwarding a campaign email the From address is the subscriber's address not the original From address. This can cause delivery problems when using services such as Amazon SES that require the From address to be verified.
There are two changes affecting forwarding a campaign email
- Use the original From address instead of the subscriber address for the From address
- Use the subscriber address for the Reply-to address
https://mantis.phplist.org/view.php?id=18075
> Use the original From address when forwarding a campaign email

- public_html/lists/admin/init.php
- public_html/lists/admin/send_core.php
- public_html/lists/admin/sendemaillib.php
- public_html/lists/config/config_extended.php
Add Reply-To header to campaign emails controlled by a config file setting.
I suspect that most people will not need to set a separate reply-to address therefore the default value of the config setting is not to display the reply-to field on the Compose tab to avoid cluttering the user interface. 
The existing code to handle reply-to allows the same variations as the From address (email address with optional name, or just name on its own) so the same help topic is used. That is updated in a separate pull request  https://github.com/phpList/phplist-lan-help/pull/26
https://mantis.phplist.org/view.php?id=20230
> Add Reply-To header to campaign emails

- public_html/lists/admin/actions/statsoverview.php
On the Statistics Overview page order by the sent date.
Change the column heading from "date" to "Date sent" to clarify which date is being displayed.
https://mantis.phplist.org/view.php?id=20239
> Mantis 20239: Sort campaigns in "statistics overview" by sent date

- public_html/lists/admin/js/phplistapp.js
- public_html/lists/admin/sendemaillib.php
When using a web page for the content of a campaign the URL may contain user placeholders. Currently the [ID] placeholder is  replaced by the message id in earlier processing instead of by the user id. This change avoids trying to replace message fields in the URL.
From the web server log when fetching the remote url
Prior to change, was using the message id
`127.0.0.1 - - [18/Aug/2020:10:41:53 +0100] "GET /webpage.html?email=foo567%40bar.com&id=168 HTTP/1.1" 200 396 "-" "phplist v3.5.6-RC1c (https://www.phplist.com)"`
Now uses the user id
`127.0.0.1 - - [18/Aug/2020:10:44:32 +0100] "GET /webpage.html?email=foo567%40bar.com&id=3012 HTTP/1.1" 200 396 "-" "phplist v3.5.5.1-devc (https://www.phplist.com)"`
Additionally, when testing whether the entered URL is valid by fetching it, the URL …
> Mantis 20247 - Do not replace message fields in a user-specific URL

- public_html/lists/admin/init.php
- public_html/lists/config/config_extended.php
- public_html/lists/index.php
I needed my ajax-based PHPList subscription forms to be working on multiple websites, so I added a new config constant called "ACCESS_CONTROL_ALLOW_ORIGINS" which is an array where you can put in your different origins you want to allow.
I also added a new header "Vary: Origin" in order to optimize cache control. (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin#CORS_and_caching)
> Ajax subscription: access-control-allow-origin for multiple websites

- public_html/lists/admin/init.php
It is about a year since PHPMailer 6 was included and could be enabled through config.php https://github.com/phpList/phplist3/pull/608
When installing phplist I have enabled PHPMailer 6 and not seen any problems so it could now be made the default.
This will affect all phplist installations, not just new installations, unless the owner explicitly disables using PHPMailer 6 through config.php
> Use PHPMailer 6 by default instead of PHPMailer 5.

- public_html/lists/admin/class.phplistmailerbase.php
Use PHPMAILER_PATH only when it appears to be valid. For PHPMailer 5 it should be a file and for PHPMailer 6 it should be a directory.
https://mantis.phplist.org/view.php?id=20286
> Avoid problem with custom PHPMailer 5 path when using PHPMailer 6

- public_html/lists/admin/init.php
- public_html/lists/admin/send_core.php
- public_html/lists/config/config_extended.php
Allow a flag to switch the Message Preview on or off.
> make message preview configurable

- public_html/lists/admin/import2.php
This forum topic  https://discuss.phplist.org/t/attributes-not-working-on-import/6768 showed an sql error when trying to import a comma separated file but not changing the field separator from TAB. This change escapes the column name when trying to match it with an attribute name.
> Avoid sql error when importing a file with the wrong field delimiter

- public_html/lists/admin/index.php
Avoid php undefined index notice when parsing command line parameters.
https://mantis.phplist.org/view.php?id=18002
> Mantis 18002 Undefined Index when calling via Command-Line

- public_html/lists/admin/importsimple.php
When importing the results disappear. This will keep them on the page.
https://mantis.phplist.org/view.php?id=20321
> change results display to info, so that the content stays on the page

- public_html/lists/admin/lib.php
Currently when a URL is shortened for display, such as to show link clicks, a leading "http://" is removed but not a leading "https://". 
Current 
After this change
> Remove leading https as well as http when shortening a URL

- doc/README.robots
- public_html/lists/config/config_extended.php
The default value of UNSUBSCRIBE_JUMPOFF , when not specified in config.php, is 1, i.e. an unsubscribe confirmation page is **not** displayed. This is different to the explanation in config_extended.php which suggests that the default is 0.
There have been reports in the user forum and Mantis about unauthorised unsubscriptions possibly due to "link following" by anti-malware software. So it seems safer to make the default not to jumpoff.
Include an explanation of how robots.txt might be used to try to stop "link following".
> Change default value of UNSUBSCRIBE_JUMPOFF

- public_html/lists/admin/lib.php
The function fetchUrl() adds to the event log in several places. In all but one case that is when VERBOSE is enabled.
In some circumstances the code checking for a new phplist release which is run on every page load can cause repeated event log records to be written.
This problem was reported in the user forum https://discuss.phplist.org/t/fetching-https-download-phplist-org-version-json-version-3-6-0-success/6989
To clarify why that particular log record is written so often. The check for a new release is on every page load but version.json should be cached in the urlcache table and retrieved only every 3 days. However, that table is emptied during processqueue. So when someone runs processqueue frequently then version.json can be retrieved much more frequently.
> Log event for fetching URL success only when verbose is enabled

- public_html/lists/admin/class.phplistmailer.php
- public_html/lists/admin/defaultsystemtemplate.php
- public_html/lists/admin/lib.php
- public_html/lists/admin/sendemaillib.php
- public_html/lists/admin/structure.php
- public_html/lists/admin/template.php
- public_html/lists/admin/upgrade.php
In https://forums.phplist.com/viewtopic.php?f=7&t=14163 a user needed to add some template-specific text to both HTML and text messages. Another user provided modifications to the code to allow for simple text templates: they were stored in their own table and had to be added manually to the database.
Building on that idea, the change proposed in this PR adds text versions of templates as first-class citizens that can be fully managed within phpList.
The default value for the text version of new templates and the value set for existing templates when the database is updated is set to `[CONTENT]`, so that phpList's behavior remains unchanged unless the user edits the text template.
This PR contains also, as separate commits, a couple of fixes I made along the way.
> Text templates

- public_html/lists/admin/messages.php
On the List Campaigns page the layout of the Processed section has gone awry.
This seems to be the result of a recent change https://github.com/phpList/phplist3/pull/727/commits/79af4592dc1bdb9c4355e61b922af64f2549af5e that removed what looked like an unnecessary sprintf % character. It turns out that % character was using up one of the parameters to sprintf, so removing it meant that the parameters were displayed in the wrong position.
> The layout of the Processed section on the List Campaigns page 

- public_html/lists/admin/languages.php
php 8 seems to be more strict about issuing warnings. These are not issued using php 7 with error reporting enabled
`[Sat Feb 27 17:32:29.350478 2021] [php:notice] [pid 15437] [client 127.0.0.1:55392] PHP Warning:  Trying to access array offset on value of type null in /home/duncan/Development/GitHub/phplist3/public_html/lists/admin/languages.php on line 360, referer: http://strontian/lists/admin/?page=home`
> Avoid php warning regarding null type

- public_html/lists/admin/connect.php
The menu item for Update is always displayed, instead of only when enabled. This is caused by a previous change trying to remove the menu item when it is not enabled not working as intended (the arrays are numerically-indexed not associatively).
https://github.com/phpList/phplist3/commit/497d66a6300f2abc286b9dc27ea425c6d1855705#diff-a58d59211ff2a40cdba18a95fa1fc84cf882767d95735f18762085ef7f02823fR809
It seems simpler to add the item when required instead of removing it when not required.
> The update menu item is displayed when it is disabled

- public_html/lists/admin/connect.php
Correct the validation of an empty string for an "emaillist" config item.
Correct the use of report_address when it is empty (the same problem of using explode() on an empty string).
https://mantis.phplist.org/view.php?id=20334
> Mantis 0020334: Can't remove email address

- public_html/lists/admin/actions/export.php
- public_html/lists/admin/export.php
When exporting subscribers using the command line and specifying a list id:
1. A message "Exporting all subscribers ..." is issued even when a list has been specified.
2. The message showing the location of the output file has an erroneous '.' character in the file path.
```
sudo -u www-data php /home/duncan/www/lists/admin/index.php -p export -l 1 -c /home/duncan/Development/PHP/phplist/config.php
phpList - phpList version 3.6.1-dev (c) 2000-2021 phpList Ltd, https://www.phplist.com
Running DEV version. All emails will be sent to xxx@yyy.co.uk
phpList - Export subscribers
phpList - *  Exporting all subscribers. Use -l[listnumber] to export subscribers on a list
phpList - File available as "/home/duncan/www/tmp./phpList subscribers on test from 2017-02-06 to 2020-12-24 (2021-Mar-04).csv" …
```
> Small issues with command line export of subscriber list

- public_html/lists/admin/users.php
On the Search Subscribers page the entered search value does not match if it has leading or trailing spaces. This might happen if the email address was copied and pasted inaccurately.
This has been requested in the user forum https://discuss.phplist.org/t/trim-blank-trailing-leading-characters-from-email-addresses-during-search-enter-etc/2359
This change simply removes any leading or trailing spaces.
> Remove leading/trailing spaces from the entered search value

- public_html/lists/admin/actions/import2.php
- public_html/lists/admin/lib.php
When importing a file of email addresses with attributes, include new lists that have been subscribe to in the user history report.
> Include new lists in the user history report when importing

- public_html/lists/admin/bounces.php
The Bounces page misleadingly shows "unknown" for the subscriber or campaign. This change is to show the bounce status and comment instead, such as for a duplicate bounce, and display "unknown" only for an unprocessed bounce.
Also, use an existing function to get the email address for a subscriber id.
https://mantis.phplist.org/view.php?id=19731
> Avoid displaying "unknown" for the subscriber and campaign on the bounces page

- public_html/lists/index.php
Don't add an entry about being removed from lists to the user history when unsubscribing, to avoid cluttering the user history. Currently two entries are added when unsubscribing, there is also an entry for being added to the blacklist.
There was an earlier change https://mantis.phplist.org/view.php?id=17753 to leave the subscriber's list membership intact when unsubscribing. But the code still adds an entry to the user history saying that they have been unsubscribed from all lists
> Don't add entry about being removed from lists to the user history

- public_html/lists/admin/plugins.php
Two small fixes to managing plugins
1) When getting a list of tags from GitHub the code doesn't handle an empty array being returned, which causes a php error to be issued.
2) A plugin installed through the admin interface can be deleted only when it has a subdirectory. Some plugins, such as phplist-plugin-campaignslicer do not have such a subdirectory. This change allows the plugin to be deleted.
> Updating and deleting a plugin

- public_html/lists/admin/PEAR/HTTP/Request2.php
- public_html/lists/admin/PEAR/HTTP/Request2/Adapter.php
- public_html/lists/admin/PEAR/HTTP/Request2/Adapter/Curl.php
- public_html/lists/admin/PEAR/HTTP/Request2/Adapter/Mock.php
- public_html/lists/admin/PEAR/HTTP/Request2/Adapter/Socket.php
- public_html/lists/admin/PEAR/HTTP/Request2/ConnectionException.php
- public_html/lists/admin/PEAR/HTTP/Request2/CookieJar.php
- public_html/lists/admin/PEAR/HTTP/Request2/Exception.php
- public_html/lists/admin/PEAR/HTTP/Request2/LogicException.php
- public_html/lists/admin/PEAR/HTTP/Request2/MessageException.php
- public_html/lists/admin/PEAR/HTTP/Request2/MultipartBody.php
- public_html/lists/admin/PEAR/HTTP/Request2/NotImplementedException.php
- public_html/lists/admin/PEAR/HTTP/Request2/Observer/Log.php
- public_html/lists/admin/PEAR/HTTP/Request2/Observer/UncompressingDownload.php
- public_html/lists/admin/PEAR/HTTP/Request2/Response.php
- public_html/lists/admin/PEAR/HTTP/Request2/SOCKS5.php
- public_html/lists/admin/PEAR/HTTP/Request2/SocketWrapper.php
- public_html/lists/admin/PEAR/PEAR/Exception.php
The version of the HTTP_Request2 package, which is used as a fall-back when curl is not enabled, is not compatible with php 8 because it uses get_magic_quotes_runtime(). This change updates the package to the latest version.
Tested with php 7.2 and php 8.0.5.
> Update HTTP_Request2 to version 2.4.2 for compatibility with php 8

- public_html/lists/admin/messages.php
When marking a message as sent, set the sent field to the current time. That is what happens when a campaign completes sending normally.
https://mantis.phplist.org/view.php?id=20354
> Mantis 20354 When marking a message as sent, set the sent field to the current time.

- public_html/lists/admin/login.php
If you add a new admin user, there is at least a small password policy of having at least 8 characters. If the admin then decides to change the password on his own via password change request, he could in theory set just a 1 character password. This fix introduces a basic input validation of the string length of both new password input fields in order to fix this security issue.
> Security enhancement: min length for password change

- public_html/lists/admin/user.php
As found in #791 
The password when editing a subscriber wasn't saved.
This change does the following:
- only display the password field when "ASKFORPASSWORD" is true (which is not default)
- save the password correctly when entered
- remove sys: in front of the password field (cosmetic)
> fix saving the password when editing a subscriber

- public_html/lists/config/config_extended.php
In config_extended.php the URL to the phpmailer documentation is out of date.
> Correct the URL to phpmailer SMTP debug documentation

- public_html/lists/admin/inc/userlib.php
php 8 issues warnings when trying to get the value of an attribute and the user does not have one.
```
[Sun Sep 26 14:42:54.045532 2021] [php:notice] [pid 10637] [client 127.0.0.1:43212]
PHP Warning:  Trying to access array offset on value of type null in /home/duncan/www/lists_3.6.4/admin/inc/userlib.php on line 419
```
> Avoid php 8 warning about trying to access null variable as an array

- public_html/lists/admin/spageedit.php
A problem reported in the user forum 
https://discuss.phplist.org/t/subscription-button-text-not-escaped/7772
> Remove slashes from the subscribe button text when editing the subscribe page

- public_html/lists/admin/sendemaillib.php
- public_html/lists/lt.php
Add analytics parameters only for http and ftp URLs when click tracking is not enabled.
When click tracking is enabled only http and ftp links are tracked. Analytic parameters are added when a link is clicked, therefore are added only to the http and ftp links, not to mailto: for example.
When click tracking is not enabled then analytic parameters are added to all links. That isn't necessary or even sensible for other protocols such as mailto:.
It also isn't wanted for a link to an element within the email itself.  The RSS Feed plugin now generates a table of contents with links like this, and doesn't want analytic query parameters to be added
<a href="#item_0">Kraft Heinz says people must get used to higher food prices</a>
> Add analytics parameters only for http and ftp URLs

- public_html/lists/admin/connect.php
- public_html/lists/admin/inc/userlib.php
- public_html/lists/admin/initialise.php
- public_html/lists/admin/lib.php
Allow calling initialise on commandline
required ENV variables:
- ADMIN_PASSWORD - password for admin account
- ADMIN_EMAIL - email address for admin account
Optional ENV variables:
- ADMIN_NAME - name of administrator
- ORGANISATION_NAME - name of organisation
Additionally, the -f parameter will force initialisation
`php public_html/lists/admin/index.php -p initialise -c [configfile] [-f]`
> Add initialise on commandline

- public_html/lists/admin/connect.php
The view admin page gives a fatal error when displaying an admin whose "password changed" date is empty. The error happens in the formatDate() function.
```
[24-Oct-2021 11:08:19 Europe/London]
PHP Fatal error:  Uncaught TypeError: Unsupported operand types: string * int in /home/dcameron/public_html/lists/admin/connect.php:1806
```
Rather than try to ensure that all callers of that function do not pass an empty date field, it is simpler just to return an empty string, which is what the formatDateTime() does already.
> Avoid php 8 fatal error when trying to format an empty date string

- public_html/lists/admin/actions/processqueue.php
- public_html/lists/admin/sendemaillib.php
Avoid php notice "Trying to access array offset on value of type null with php 8
```
[Sat Oct 23 07:46:31.488993 2021] [php7:notice] [pid 4211] [client 127.0.0.1:40156]
PHP Notice:  Trying to access array offset on value of type null in /home/duncan/www/lists_3.6.5/admin/sendemaillib.php on line 1293, referer: http://strontian/lists/admin/?page=processqueue&tk=b4c88a1a3bad03da11899675a688835a
[Sat Oct 23 08:11:28.592318 2021] [php7:notice] [pid 3760] [client 127.0.0.1:40404]
PHP Notice:  Trying to access array offset on value of type null in /home/duncan/www/lists_3.6.5/admin/actions/processqueue.php on line 631, referer: http://strontian/lists/admin/?page=processqueue&tk=b4c88a1a3bad03da11899675a688835a
```
> Avoid php 8 notices when trying to access a null value as an array

- public_html/lists/admin/editlist.php
- public_html/lists/admin/list.php
When listing the lists or editing a list the list id is not displayed. The id is needed when for example setting up an ajax subscribe form.
Also, removed an unnecessary form start tag, and unused hidden form field for id because id is taken from the GET parameter.
When showing all lists
When editing a list
> Show list id when displaying lists

- public_html/lists/admin/upgrade.php
I was looking at the message table and noticed that the processed column was set to null, even when campaigns had been sent.
An earlier change had changed the column from medium int to integer, but when upgrading existing databases the "change column" syntax changes the whole column definition, not just the data type. So the previous default value was lost.
https://github.com/phpList/phplist3/commit/ff53c6f66dd63d8b2f98a5ee541a965a52e77360#diff-69b8033d3d4d2e49f71cd4b938df9fbca5ebe89b3ae860927f8748e9854570e9
In my database, all campaigns sent since applying that update had the processed column set to null, which stopped sql statements like this from working
set processed = processed + 1
This change will restore the default value of 0. Strictly it is needed only for databases that had the …
> Set default of 0 for the processed column in the message table.

- public_html/lists/admin/actions/import2.php
Currently when importing an existing subscriber with a new attribute value, i.e. they do not have a value for that attribute, the change is not reported in the user history. This is caused by the code not reporting changes where the old value is "false" such as null or an empty string.
This change is to always report a new or changed attribute value.
Before this code change, the change of attribute value is not reported
After this code change, the change of attribute value is reported with an empty "previous value".
> When importing report an attribute value changing from null.

- public_html/lists/index.php
3.66, php8
When entering the user subscription page: white screen of death as count is operating on a string, not the array.
> bugfix count on a string

- public_html/lists/admin/editattributes.php
The textarea field of new attributes has \r\n as line endings but the code currently splits on only \n.
https://github.com/phpList/phplist3/issues/839
> Use \r\n to split the new attributes textarea field

- public_html/lists/admin/inc/interfacelib.php
I noticed that in the Campaign listings there is bottom pagination already but I didn't see any when using the Search subscribers.  I think it will be useful to add there also and it seems like a small change.
> Add bottom pagination in search subscribers page

- public_html/lists/admin/mysqli.inc
In php 8.1 there is a change to the mysql default error mode. An exception is now thrown instead of silencing the error.
See https://php.watch/versions/8.1/mysqli-error-mode for an explanation.
This causes a problem for code that, for example, inserts a row without checking whether a row with the key already exists.
The simple import page has such code, and with php 8.1 trying to insert an email address that already exists causes a fatal error.
`[Fri Feb 04 17:59:19.730045 2022] [php:notice] [pid 2005] [client 127.0.0.1:53550] PHP Fatal error:  Uncaught mysqli_sql_exception: Duplicate entry 'foo1@test.com' for key 'email' in /home/duncan/Development/GitHub/phplist3/public_html/lists/admin/mysqli.inc:179`
This PR changes the default mode to that used prior to php 8.1 so that the current …
> Set mysql error reporting to the pre-8.1 value

- public_html/lists/admin/lib.php
The report emails sent to an admin, such as process queue report and bounce processing report, include the installation name in the subject. See https://github.com/phpList/phplist3/blob/master/public_html/lists/admin/connect.php#L396
This change is to do the same for the notification emails sent to an admin when a subscriber subscribes, unsubscribes etc.
> Prepend the installation name to the subject of notification emails

- public_html/lists/admin/processbounces.php
Currently when a subscriber is deleted by a bounce rule the bounce report includes a link to the now non-existent subscriber page.
This PR changes the report to show only the email address and also adds the subscriber id, which might be useful extra information.
> In the bounce report do not link to a deleted subscriber

- public_html/lists/admin/structure.php
- public_html/lists/admin/upgrade.php
Increase 'loginname' max chars to 66 on admin table.
The following changes are being made in order to solve the issue> `loginname` character limit , related to SSO plugin.
The discussion can be found here https://github.com/phpList/phplist-plugin-simplesaml/issues/2
> Increase column size (admin table) on DB

- public_html/lists/admin/actions/import2.php
- public_html/lists/admin/import.php
- public_html/lists/admin/import2.php
The import of a file from the command line currently fails with `Error: Invalid security token, please reload the page and try again`
I suspect this is due to the splitting of import into two pages when adding the "action" page, so has not worked for a long time.
This change is to run the import2 page followed by the actions/import2 page.  Trying to use only the action page doesn't work because it is closely tied to the first page which sets various $_SESSION variables.
Some unnecessary browser output leaks through see screenshot below but isn't too distracting.
```
Reading emails from file .....ok, 3 linesReading emails from file .....ok, 3 lines<script type="text/javascript">
var parentJQuery = window.parent.jQuery;
parentJQuery("#progressbar").updateProgress("0,2");
</script>
All the …
```
> Importing subscriber file from the command line

- public_html/lists/admin/users.php
I am using phpList along with attributes in the Greek language and in the search subscribers section the filtering dropdown which shows the available attributes doesn't correctly truncate Greek strings due to the substr command.
I propose to change it with the function shortenTextDisplay (defined in lib.php) which uses the corresponding mb_ versions for substr etc. if available.
**Before:**
**After:**
> Better support for non-latin strings in select dropdown of search subcribers page

- public_html/lists/admin/inc/userlib.php
Using php 8 a deprecation warning is issued when using stripslashes() on a null attribute value
`[Sun Sep 11 21:30:33.465091 2022] [php:notice] [pid 3075] [client 127.0.0.1:44934] PHP Deprecated:  stripslashes(): Passing null to parameter #1 ($string) of type string is deprecated in /home/duncan/www/lists_3.6.8/admin/inc/userlib.php on line 469, referer: http://strontian/lists/admin/?page=send&id=262&tk=834f3409237077f6681686b186501f4e`
The attribute value really is null, so it needs to be converted to a string.
> Avoid php 8 deprecation for a null attribute value

- public_html/lists/admin/pluginlib.php
The code in pluginlib.php looks for nested "plugins" directories for each file or directory in the plugins directory
`} elseif (is_dir($pluginRootDir.'/'.$file.'/plugins')) {`
When open_basedir is in effect, php issues a number of warnings when $file is a file not a directory.
Not sure whether this code path is now needed. I think that it is there for development when using PLUGIN_ROOTDIRS.
> Avoid php warnings when open_basedir is enabled.

- public_html/lists/admin/defaultplugin.php
- public_html/lists/admin/onyxrss/onyx-rss.php
In php 8.2 using an undeclared class variable is deprecated. 
`PHP Deprecated:  Creation of dynamic property CKEditorPlugin::$origin is deprecated in /home/duncan/www/lists_3.6.10/admin/pluginlib.php on line 81`
> Avoid php 8.2 warning about dynamic properties

- public_html/lists/admin/actions/processqueue.php
There have been some reports of divide by zero exceptions when using php 8.
https://discuss.phplist.org/t/v-3-6-10-with-php-8-0-x-problems/8526/14
This change fixes one possible cause. I think that if the timer elapsed() call is within the same microsecond as the start() then the elapsed time will be returned as 0.
> Avoid possible divide by zero when calculating message send rate

- public_html/lists/admin/lib.php
- public_html/lists/admin/mclicks.php
- public_html/lists/admin/members.php
- public_html/lists/admin/mviews.php
- public_html/lists/admin/uclicks.php
- public_html/lists/admin/userclicks.php
This change (by me) from 2013 to use a zero-width space to allow wrapping of an email address seems to have caused a bit of confusion and wasted time https://github.com/phpList/phplist3/commit/996c3ce78ef4dda61916224886cfac48583e5c51  
People have been copying an email address from a statistics page, then pasting that into the search field on the Subscribers page. Because of the zero-width space the subscriber is not found.
A better approach is to use the `<wbr>` element immediately after a character where we want to allow wrapping. Copying/pasting an email address includes only the characters of the email address, not the `<wbr>` element.
This pull request
- changes the shortenTextDisplay() function to handle only text fields
- adds a similar shortenEmailDisplay() function which uses the …
> Improve wrapping of email addresses

- public_html/lists/admin/connect.php
There have been reports in the user forum about phplist failing after sending only one email https://discuss.phplist.org/t/v-3-6-10-with-php-8-0-x-problems/8526/16 .
One report  https://discuss.phplist.org/t/campaign-stops-after-1-email-if-language-is-not-englisch/8627  narrowed it down to being related to the language, German in his case. Selecting English made the problem stop happening.
Looking more closely at the output provided showed comma being used as the decimal separator
```
Found them: 4 to process
Sending 2 to ab.c@xxx.yy
It took 0,0898380000 seconds to send
```
The timer class is returning the result of sprintf using the %f specifier, which is locale specific, causing a comma to be used for the decimal separator depending on the locale. The specifier %F needs to be used to …
> Make the results of the timer class use period as the decimal point

- public_html/lists/admin/init.php
increase default message age, so that repeated campaigns don't expire
#911
> set DEFAULT_MESSAGE to 8 days

- public_html/lists/admin/sendemaillib.php
This change is to try to fix a problem with the CKEditor plugin when people want to edit messages as HTML full pages.
The default for CKEditor is to allow only limited html. If you want to edit a full page including head, body elements etc, then a configuration option needs to be set `fullPage: true`. Currently the plugin allows that to be set for templates or for messages but not both, on the basis that structural html (head, body elements etc) would appear twice when a message is included into a template.
That option can be set for editing a template as that will always be an HTML page, but can create a difficulty when editing a message. It is fine if the admin always uses templates as the option for messages can be turned-off, and is fine if the admin never uses templates in which case …
> Use the content of the body element when including message into a template

- public_html/lists/admin/lib.php
during bounce processing the function output() can be called without be defined
this is my call stack ( 3.6.13-RC1 )
( ! ) Error: Call to undefined function output() in /var/www/html/bollettino/lists/admin/lib.php on line 962
Call Stack
#	Time	Memory	Function	Location
1	0.0001	394128	{main}( )	.../index.php:0
2	0.0158	949696	include( '/var/www/html/bollettino/lists/admin/processbounces.php )	.../index.php:759
3	0.0158	933424	getPageLock( $force = ??? )	.../processbounces.php:488
Calling the function only if it was already declared
> protect the invocation of the function output()

- public_html/lists/admin/languages.php
A few commits to tidy-up the languages.php file by removing redundant or obsolete code.
With open_basedir() in effect, I noticed warnings about trying to access the root directory
```
PHP Warning:  is_dir(): open_basedir restriction in effect. File(/lan/) is not within the allowed path(s):
PHP Warning:  is_dir(): open_basedir restriction in effect. File(/) is not within the allowed path(s):
```
Looking into this, it was caused by trying to derive a plugin's own language directory, which I think is now obsolete.
For clarity, there are four commits each removing some code that I think is not needed now.
1) Plugins have not yet been created when the `phplist_I18N` constructor is called. So the chunk of code trying to derive the
plugins basedir is redundant.
2) The code in the constructor …
> Remove obsolete code from languages.php

- TESTING.md
- Vagrantfile
- public_html/lists/admin/accesscheck.php
- public_html/lists/admin/admin.php
- public_html/lists/admin/adminattributes.php
- public_html/lists/admin/admins.php
- public_html/lists/admin/connect.php
- public_html/lists/admin/importadmin.php
- public_html/lists/admin/index.php
- tests/features/getting-started/menu.feature
non Superusers should not be allowed to manage admins, even when they have "config" permissions
> disallow non-Superusers to manage admins

- public_html/lists/admin/index.php
Currently the -c parameter has to be used when running from the command line. This is now unnecessary because the config file in the default location will be used if it exists and the -c parameter is not present.
Issue #719 raised the question of using the config file in the default location. That has already been changed but the test for the -c parameter was left in making it mandatory.
> Use config.php in the default location when using command line

- public_html/lists/admin/actions/configure.php
When editing a boolean item on the Settings page, such as "Send notifications about subscribe, update and unsubscribe", the select list of Yes and No should show the current value but shows Yes when the current value is actually No. 
The code to select No is now incorrect due to php 8 being stricter about comparisons.
The value for a boolean seems to be "1" for true and an empty string for false. Previously `$value == 0` would also be true when $value is an empty string.
if ($value === false || $value == 'false' || $value == 0) {
> Correct display of a select list for a boolean config item

- public_html/lists/admin/message.php
When a campaign is resent to additional lists on the Message page, the messageReQueued() method is not currently called.
This change adds the same processing as in used when a campaign is requeued on the Campaigns page
> Call the messageReQueued() method when a campaign is resent

- composer.lock
Update the composer.lock file to use the latest CKEditor, Common and Updater plugins.
> Update CKEditor, Common and Updater plugins

- public_html/lists/admin/actions/processqueue.php
When using domain throttling, if sending to an email address is rejected because the limit on its domain has been reached  and an email was not sent, the delay of `MAILQUEUE_THROTTLE` is still applied. This seems unnecessary and slows down the sending rate.
The first commit is to apply `MAILQUEUE_THROTTLE` and `MAILQUEUE_AUTOTHROTTLE` only when the domain was not throttled. 
I don't fully understand the `$running_throttle_delay` processing so have left that as it is.
The second commit is to simplify the initialisation of the `$domainthrottle` array into one place, when a new domain is met or a new interval is started for an existing domain.
> When using domain throttling, apply delay only when email was sent

- public_html/lists/admin/init.php
- public_html/lists/admin/processbounces.php
- public_html/lists/config/config_extended.php
Allow some hard-coded settings to be specifed in config.php
- maximum number of bounces to retrieve from the mailbox, default is 100,000
- the number of bounces to process in one batch for bounce rules, default is 500
- the name of the mailbox, default is INBOX
Further, allow more than one mailbox to be specified. This is useful to be able to retrieve bounces that have been put in a Junk folder on the server.
> Replace constants in the bounce handling code by config.php settings

- public_html/lists/admin/bouncemgt.php
- public_html/lists/admin/lib.php
- public_html/lists/admin/processbounces.php
1. Added support for processing bounces without downloading new bounces (great for testing rules!)
1. Added support for a new bounce rule action that allows defining cases when that should undo automatic actions (this connects to point 1 when you accidentally unconfirm subscribers and wish to test how not to do it again without affecting bounces that were to be affected since they weren't downloaded yet)
> Bouncemgt - allowing processing only existing bounces + a related new rule action

- public_html/lists/admin/send_core.php
The error message returned by a plugin from `allowMessageToBeQueued()` needs to have any single-quote character escaped because it is within a javascript literal.
> Escape single quote in error message returned by allowMessageToBeQueued()

- public_html/lists/admin/connect.php
Allow ajax page links to have a title, defaulting to the link description. The title is shown when hovering over the link.
Currently an ajax link has a misleading title attribute. The title is set to that for the target page, but the link is always for a specific action on that page. See the screenshot for the Generate link.
This change adds an optional `$title` parameter to the `PageLinkAjax()` function then uses that or the `$desc` parameter for the call to `PageLink2()`.
This allows the calls to `PageLinkAjax()` to be updated later to have a meaningful title when needed.
> Allow ajax page links to have a title

- .github/workflows/build-release.yml
- .github/workflows/main.yml
- composer.json
Add imap2 plugin to default plugin list
https://github.com/phpList/phplist3/issues/1061
> ISSUE-341: add imap2 plugin

- composer.json
- composer.lock
Use new plugin with elFinder file manager
https://github.com/phpList/phplist3/issues/1062
> ISSUE-340: add ckeditor5
